### ISSUE TITLE
常见问题

### ISSUE THREAD

**Issue by 4x99** [4x99/code6#1]
### 1. 创建用户时提示 `Connection refused`
原因：Docker 容器连不上 MySQL，请通过以下方式排查：
- 确认 `MYSQL_HOST` 是否设置为 `127.0.0.1`，容器无法通过 `127.0.0.1` 连接宿主机，可在宿主机执行 `ifconfig` 或 `ip addr` 查看 `docker0` 的 IP，将 `MYSQL_HOST` 设置为此 IP
- 确认 iptables 及防火墙是否限制连接
- 确认 MySQL 是否已给 `MYSQL_USERNAME` 用户授权，授权命令：`GRANT ALL PRIVILEGES ON *.* to <MYSQL_USERNAME>@'%' identified by '<password>';`（请根据实际情况授权）
- 确认 MySQL 配置文件的 `bind-address` 参数是否绑定 `127.0.0.1`，如果有则注释并重启

解决后，删除当前容器，创建新容器即可，或者在当前容器执行 `php artisan migrate` 导入数据表。

---

### 2. 在 GitHub 创建令牌时，`Select scopes` 部分的权限需要勾选哪些？
都不用勾选。 

---

### 3. 可以用同一个 GitHub 账号创建多个令牌吗？
不能，这种情况多个令牌共享账号配额，需要注册多个 GitHub 账号（建议不要在同一环境批量注册，容易被 GitHub 标记异常）。

---

### 4. [ 令牌配置 ] 模块中的令牌配额为何有多有少？
正常 GitHub 令牌请求配额为 30 次 / 分钟，如果小于此值，可能账号已被 GitHub 标记为异常（注册多个账号容易被 GitHub 检测标记）

---

### 5. 日志报错：`“cURL error 7: Failed connect to api.github.com:443; Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)”`
国内网络环境请求 GitHub API 有时会失败，不是大量且频繁出现可以忽略。当然，将系统部署到海外或使用海外代理会更加稳定。

---

### 6. 为何 [ 令牌配置 ] 中的令牌状态时而正常时而异常？
同上一个问题，如长时间处于异常状态，请检查令牌是否真的异常。

---

### 7. 扫描代码有哪些限制和注意事项？
请阅读 GitHub 文档：[代码搜索的注意事项](https://help.github.com/cn/github/searching-for-information-on-github/searching-code#considerations-for-code-search)

---

### 8. 扫描到泄露代码但联系不上仓库拥有者怎么办？
可通过 [GitHub DMCA](https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/)（数字千年版权法）在线联系 GitHub 下架：https://support.github.com/contact/dmca-takedown

---

### 9. 钉钉群机器人安全设置如何配置？
不支持加签，可选：
- 自定义关键词
- IP 地址（段）

---

### 10. Docker 启动容器时 PHP 安装扩展失败
将 Docker 升级到 20+ 版本后重新安装

---

### 11. 使用 Docker-Compose 部署时无法从阿里云镜像安装包
报错内容为：
```
Failed to fetch http://mirrors.aliyun.com/...
```
宿主机配置 Docker DNS 后重新部署：
```
vim /etc/docker/daemon.json
```
```
{                                                                          
    "dns": ["223.5.5.5", "8.8.8.8"]                                                                           
}
```

**Comment by adkinguzi** [comment]
换了个系统很快弄好了 ，就是账户密码没问题 也没提示错误，就是登录不上去!

**Comment by yoonper** [comment]
> 换了个系统很快弄好了 ，就是账户密码没问题 也没提示错误，就是登录不上去!

storage/logs/code6.log 看看有没报错日志
方便留个联系方式吗？我帮你看看

**Comment by adkinguzi** [comment]
qq:2320281792

**Comment by KangD1W2** [comment]
请问数据库表结构怎么建？

**Comment by yoonper** [comment]
> 请问数据库表结构怎么建？

启动容器的时候自动创建，如果启动时数据库连接不上则创建失败，可以重新启动一个容器或者在当前容器执行：
```
php artisan migrate
```

**Comment by KangD1W2** [comment]
docker搭建，没有自动创建表结构，报错：Base table or view not found: 1146 Table 'code6.user' doesn't exist

**Comment by KangD1W2** [comment]
> > 请问数据库表结构怎么建？
> 
> 启动容器的时候自动创建，如果启动时数据库连接不上则创建失败，可以重新启动一个容器或者在当前容器执行：
> 
> ```
> php artisan migrate
> ```

docker搭建，没有自动创建表结构，报错：Base table or view not found: 1146 Table 'code6.user' doesn't exist

**Comment by KangD1W2** [comment]
> > > 请问数据库表结构怎么建？
> > 
> > 
> > 启动容器的时候自动创建，如果启动时数据库连接不上则创建失败，可以重新启动一个容器或者在当前容器执行：
> > ```
> > php artisan migrate
> > ```
docker搭建，他没自动创建表结构，输了php artisan migrate就创建表结构了，可以新建登录用户了，谢谢。

**Comment by KangD1W2** [comment]
> > > > 请问数据库表结构怎么建？
> > > 
> > > 
> > > 启动容器的时候自动创建，如果启动时数据库连接不上则创建失败，可以重新启动一个容器或者在当前容器执行：
> > > ```
> > > php artisan migrate
> > > ```
> 
> docker搭建，他没自动创建表结构，输了php artisan migrate就创建表结构了，可以新建登录用户了，谢谢。
> 输了php artisan migrate之后出现SQLSTATE[HY000] [2002] No route to host (SQL: select * from information_schema.tables where table_schema = code6 and table_name = migrations and table_type = 'BASE TABLE')，是数据库没连上吗？重启了数据库和docker都不行。

**Comment by yoonper** [comment]
@KangD1W2 数据库没连接上，请参照常见问题第 1 点处理，如果无法解决麻烦留个 QQ 看下~

**Comment by KangD1W2** [comment]
> @KangD1W2 数据库没连接上，请参照常见问题第 1 点处理，如果无法解决麻烦留个 QQ 看下~

>OK，看第1点解决了，关闭了防火墙就可以，感谢。

**Comment by P-udding** [comment]
请问一下 使用源码部署 扫描不到结果，查看日志job-run.log 发现出现`production.INFO: Start job   production.ERROR: No GitHub client available  ` 这是什么问题

**Comment by yoonper** [comment]
> 请问一下 使用源码部署 扫描不到结果，查看日志job-run.log 发现出现`production.INFO: Start job production.ERROR: No GitHub client available ` 这是什么问题

网络问题，国内网络环境请求 GitHub API 不稳定，可以把扫描间隔调小一些，或者加代理。

**Comment by pudidng** [comment]
> > 请问一下 使用源码部署 扫描不到结果，查看日志job-run.log 发现出现`production.INFO: Start job production.ERROR: No GitHub client available ` 这是什么问题
> 
> 网络问题，国内网络环境请求 GitHub API 不稳定，可以把扫描间隔调小一些，或者加代理。

在同一台服务器 通过源码部署会出现`ERROR: No GitHub client available ` 但是通过docker部署就可以成功 这是什么问题

**Comment by yoonper** [comment]
出现 `ERROR: No GitHub client available` 说明码小六用令牌去请求 GitHub 时出现了错误，原因有以下几个：
1. 网络问题（时而能连上时而连不上）
2. Token 有问题（用 GitHub 账号登录 GitHub 顶部会有红色字提醒账号被标记为异常）

一般和 Docker 部署或者源码部署关系不大

**Comment by 1806961944** [comment]
“待执行任务”如何后台删除？

**Comment by yoonper** [comment]
> “待执行任务”如何后台删除？

扫描任务执行完毕后会自动删除，如果想手动删除则清空 `queue_job` 表。

**Comment by byr0nchan** [comment]
令牌显示未同步，如何排查。同一令牌在另一容器环境中正常

**Comment by yoonper** [comment]
> 令牌显示未同步，如何排查。且一直显示待执行任务。同一令牌在另一容器环境中正常

检查下 CRON 是否正常运行，此外可以进入 Docker 容器看下运行日志：
```
docker exec -it code6-server /bin/bash
cd storage/logs
```
日志名称：`job-run-日期.log`

**Comment by 163-code** [comment]
邮箱通知，每次监控新增文件或者仓库事件，都同时间发送6封邮件通知，且时间一致

**Comment by WLLRQ520** [comment]
数据库连不上，麻烦大佬看下
qq:1935626301

**Comment by yoonper** [comment]
> 数据库连不上，麻烦大佬看下
> qq:1935626301

请先按第 1 点尝试解决。

**Comment by WLLRQ520** [comment]
已经按第一点解决了，但还是连不上

**Comment by yoonper** [comment]
> 邮箱通知，每次监控新增文件或者仓库事件，都同时间发送6封邮件通知，且时间一致

麻烦提供一下日志
```
docker exec -it code6-server /bin/bash
cd storage/logs
```
日志名称：`notify-日期.log`

**Comment by 163-code** [comment]
> > 邮箱通知，每次监控新增文件或者仓库事件，都同时间发送6封邮件通知，且时间一致
> 
> 麻烦提供一下日志
> 
> ```
> docker exec -it code6-server /bin/bash
> cd storage/logs
> ```
> 
> 日志名称：`notify-日期.log`

16：05分邮箱收到6封邮件：
[2021-03-11 16:05:02] production.INFO: Start notify  
[2021-03-11 16:05:02] production.INFO: Start notify  
[2021-03-11 16:05:02] production.INFO: Start notify  
[2021-03-11 16:05:02] production.INFO: Start notify  
[2021-03-11 16:05:02] production.INFO: Start notify  
[2021-03-11 16:05:02] production.INFO: Start notify  
[2021-03-11 16:05:02] production.INFO: Send complete {"type":"email","success":true} 
[2021-03-11 16:05:02] production.INFO: Close notify  
[2021-03-11 16:05:02] production.INFO: Send complete {"type":"email","success":true} 
[2021-03-11 16:05:02] production.INFO: Close notify  
[2021-03-11 16:05:02] production.INFO: Send complete {"type":"email","success":true} 
[2021-03-11 16:05:02] production.INFO: Close notify  
[2021-03-11 16:05:04] production.INFO: Send complete {"type":"email","success":true} 
[2021-03-11 16:05:04] production.INFO: Close notify  
[2021-03-11 16:05:04] production.INFO: Send complete {"type":"email","success":true} 
[2021-03-11 16:05:04] production.INFO: Close notify  
[2021-03-11 16:05:13] production.INFO: Send complete {"type":"email","success":true} 
[2021-03-11 16:05:13] production.INFO: Close notify  
[2021-03-11 16:06:01] production.INFO: Start notify

**Comment by skr-rks** [comment]
请问下。通过docker部署的方式，更新代码后重新拉去镜像创建容器，连接数据库。之前创建的任务和白名单请问都还在吗？

**Comment by yoonper** [comment]
> 请问下。通过docker部署的方式，更新代码后重新拉去镜像创建容器，连接数据库。之前创建的任务和白名单请问都还在吗？

在的，任务和白名单存储在 MySQL 中。

**Comment by 0rzNuII** [comment]
使用php artisan code6:user-add命令新建用户时报了一下错：

In Connection.php line 671:

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: sel
  ect * from `user` where (`email` = xxx@mail.com) limit 1)


In Connector.php line 70:

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known


In Connector.php line 70:

  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by yoonper** [comment]
数据库连接错误，`MYSQL_HOST` 填写的不是 IP 吗？

**Comment by 0rzNuII** [comment]
> 数据库连接错误，`MYSQL_HOST` 填写的不是 IP 吗？

不是，我连接的是docker内部的mysql

**Comment by yoonper** [comment]
添加一下 DNS 试试？

**Comment by 0rzNuII** [comment]
> 添加一下 DNS 试试？

大佬，就有个问题，这个软件在docker里运行，连接的是docker的mysql，还是宿主机的mysql?
如果是docker的mysql，那也就是说我需要pull一个mysql的镜像对吧？
（希望大佬别介意，我就是想确认一下~）

**Comment by yoonper** [comment]
都可以，甚至远程 MySQL 也可以~
如果是 Docker MySQL 需要将 MySQL 数据映射到宿主机磁盘做持久化

**Comment by 0rzNuII** [comment]
![image](https://user-images.githubusercontent.com/40875899/131982423-8b6aa7b9-48dc-43ca-8d8d-fe0b98e8884e.png)
不管执行什么命令都提示连接被拒绝……docker连接宿主机的方式，宿主机的mysql也做了对docker的授权……
![image](https://user-images.githubusercontent.com/40875899/131982567-2bc2f132-6764-4a45-9838-0663611e6208.png)
![image](https://user-images.githubusercontent.com/40875899/131982690-7b9c0a4e-aabd-4b4a-a0f0-9b700e7bc428.png)
![image](https://user-images.githubusercontent.com/40875899/131982751-003e5a33-8d67-4d26-ba70-b3fbc5ca3161.png)
各种不行……

**Comment by yoonper** [comment]
参考下置顶第 1 点

**Comment by Xia0Ny1** [comment]
卧槽，要么数据库报 SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `user` where (`email` = xiaoyi@xynh.ink) l
  imit 1)，要么就是拒绝连接……我吐了……

**Comment by 0rzNuII** [comment]
采用连接docker mysql的方法，能连上数据库，但是执行后续导入数据等和创建账号时，就开始报：
In Connection.php line 671:

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: sel
ect * from user where (email = xxx@mail.com) limit 1)

In Connector.php line 70:

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

In Connector.php line 70:

PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known

的错误；

如果采用连接外部数据库，就会开始报拒绝连接，各种调试都做了，就是连不上……我他妈的，吐了……

**Comment by zctqwq** [comment]
令牌连接时，一直令牌状态同步中

**Comment by yoonper** [comment]
> 令牌连接时，一直令牌状态同步中

通常是服务器访问 GitHub 网络不通畅。

**Comment by FFFFFFFFFA** [comment]
> > 令牌连接时，一直令牌状态同步中
> 
> 经常是服务器访问 GitHub 网络不通畅。

代理配置的文档可以提供下吗

**Comment by yoonper** [comment]
> 代理配置的文档可以提供下吗

在 “配置中心” - “代理配置” 中填入代理地址及端口
也可以将码小六部署到海外主机

**Comment by FFFFFFFFFA** [comment]
下次扫描时间更新，最近扫描时间为空，job-run 无日志报错
![image](https://user-images.githubusercontent.com/46803037/142588263-c26a56ae-4a2c-4dd5-a858-61bfe76a239d.png)
![image](https://user-images.githubusercontent.com/46803037/142588319-56a4dfb9-b162-4c42-a308-3be9be5f2f06.png)

**Comment by yoonper** [comment]
> 下次扫描时间更新，最近扫描时间为空，job-run 无日志报错 ![image](https://user-images.githubusercontent.com/46803037/142588263-c26a56ae-4a2c-4dd5-a858-61bfe76a239d.png) ![image](https://user-images.githubusercontent.com/46803037/142588319-56a4dfb9-b162-4c42-a308-3be9be5f2f06.png)

- 检查 CRON 是否正常，
- 如果与 GitHub 网络不通畅，无可用 GitHub 令牌也无法扫描

有问题尽量提交新的 issue 哈

**Comment by FFFFFFFFFA** [comment]
OK 新问题：
扫描时间正常，最近扫描时间为空。令牌正常，cron正常。目前日志没有相关记录。但是之前我重启了容器。重启容器之前日志是正常写入

**Comment by yoonper** [comment]
> OK 新问题： 扫描时间正常，最近扫描时间为空。令牌正常，cron正常。目前日志没有相关记录。但是之前我重启了容器。重启容器之前日志是正常写入

删除容器，重新启动一个试试

**Comment by ce-automne** [comment]
总算用户创建成功了。
docker创建，如果在容器里执行php artisan code6:user-add提示如下报错：
SQLSTATE[HY000] [1045] Access denied for user 'leon'@'172.17.0.2' (using password: NO) 

那么vim .env看看当前容器的DB_PASSWORD字段是否为空，如果为空，那就补上数据库的密码，然后再php artisan migrate导入表结构即可，其他问题可参考上面的[常见问题]进行解决。

**Comment by 1806961944** [comment]
你好：
      这是来自 陈昺润 的电子邮件，您的来信已受到，稍后会做仔细了解，谢谢。
                     在此祝你身体健康、天天开心0~0

**Comment by mttsyj** [comment]
任务队列一直为空，扫描任务下发不成功
![image](https://user-images.githubusercontent.com/21242222/206417052-74e627ab-681a-4e85-9c6b-f7d3fe135e2a.png)

**Comment by 1806961944** [comment]
你好：
      这是来自 陈昺润 的电子邮件，您的来信已受到，稍后会做仔细了解，谢谢。
                     在此祝你身体健康、天天开心0~0

**Comment by zhangk64** [comment]
![image](https://user-images.githubusercontent.com/29709035/222064653-7e4868c9-2d27-4b3f-8834-3d54013eeb34.png)
容器部署的方式，重启容器，再登录会出现bug。

**Comment by 1806961944** [comment]
你好：
      这是来自 陈昺润 的电子邮件，您的来信已受到，稍后会做仔细了解，谢谢。
                     在此祝你身体健康、天天开心0~0

**Comment by yoonper** [comment]
@zhangk64 麻烦通过 [New issue](https://github.com/4x99/code6/issues/new) 提交问题

**Comment by zhangk64** [comment]
> @zhangk64 麻烦通过 [New issue](https://github.com/4x99/code6/issues/new) 提交问题

1
