### ISSUE TITLE
关于请求api

### ISSUE THREAD

**Issue by xtzxtz** [4x99/code6#115]
请问这个系统可以通过api请求的方式进行调取结果和进行查询吗

**Comment by yoonper** [comment]
目前是通过 GitHub API 进行扫描

**Comment by xtzxtz** [comment]
可以通过api调用系统进行github的api扫描吗，我这边想把这个功能集成到我的一个扫描器的功能中

**Comment by yoonper** [comment]
我懂你意思了，刚刚理解错误
目前还不行，你只能配置好扫描任务，然后通过读数据库的方式获取扫描结果
