### ISSUE TITLE
使用nginx配置路径到public目录，login页显示404

### ISSUE THREAD

**Issue by JeniTurtle** [4x99/code6#116]
![image](https://user-images.githubusercontent.com/15798752/119598501-a793bd00-be15-11eb-9cdf-d957a042fb66.png)

**Comment by yoonper** [comment]
请参考 #20

**Comment by JeniTurtle** [comment]
回答好快！我刚找到原因，laravel的nginx配错了，给力！

**Comment by JeniTurtle** [comment]
@yoonper 问一下，有交流群吗，或者有qq吗

**Comment by JeniTurtle** [comment]
找到了。。

**Comment by yoonper** [comment]
暂时还没有建群

**Comment by JeniTurtle** [comment]
@yoonper 大佬，我qq找你了，你没回我。还有一个问题。
![image](https://user-images.githubusercontent.com/15798752/119607157-635ce880-be26-11eb-976b-c824d9296d5b.png)
![image](https://user-images.githubusercontent.com/15798752/119607179-6b1c8d00-be26-11eb-81f3-e5d1dc7a37a6.png)
任务日志应该已经走了，但是没有扫描数据

**Comment by yoonper** [comment]
我没有收到好友申请，Q：50663950
没有扫描数据可能是未到任务启动时间，比如 30 分钟扫描一次，将会在 14:00 14:30 .. 启动，与 CRON 启动时间机制一样

**Comment by JeniTurtle** [comment]
谢谢🙏！不过我是手动执行的任务
