### ISSUE TITLE
数据库错误

### ISSUE THREAD

**Issue by Byc4i** [4x99/code6#126]
docker 部署提示
`
In Connection.php line 671:
                                                                                                                  
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `user` where (`email` = admin@test.com) limit 1)  

In Connector.php line 70:
                                             
  SQLSTATE[HY000] [2002] Connection refused 
`
docker logs 提示
`
Application key set successfully.

In Connection.php line 671:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
  chema.tables where table_schema = code6 and table_name = migrations and tab  
  le_type = 'BASE TABLE')                                                      
                                                                               

In Connector.php line 70:
                                             
  SQLSTATE[HY000] [2002] Connection refused 
`

**Comment by yoonper** [comment]
源码部署吗？

**Comment by yoonper** [comment]
检查一下 `.env` -> `DB_*` 配置是否正确

**Comment by Byc4i** [comment]
我先去看看常见问题
