### ISSUE TITLE
码小六升级问题

### ISSUE THREAD

**Issue by test502git** [4x99/code6#128]
码小六之前是docker搭建的，请问如何做到平滑升级到最版版本，请指教 谢谢

**Comment by yoonper** [comment]
1.5.0 及之前版本直接拉最新代码，重新创建镜像启动容器即可
1.5.1 及之后最好备份一下 `[ 白名单配置 ]` - `[ 按文件名忽略 ]` 配置

**Comment by test502git** [comment]
加个一键更新按键吗？

**Comment by yoonper** [comment]
暂时应该不会有一键更新

**Comment by test502git** [comment]
邮箱通知时，建议把泄露详细内容也带上，这样就不会每次都登录web平台查看

**Comment by yoonper** [comment]
这个议题之前我们已经讨论过，目前只推送泄露记录数的原因有：
1. 大部分推送通道有长度限制
2. 详细内容展示效果不如 Web 页面
3. 我们希望每一条扫描记录都有生命状态（设置状态）
4. 不利于团队协作（多人重复处理同一记录）

我们也做了一些优化，比如保存用户登录状态、新增移动版，方便用户更便捷浏览扫描记录。

**Comment by test502git** [comment]
登录是一个很麻烦的过程

**Comment by yoonper** [comment]
v1.5.1 开始默认保持 7 天登录状态
可以通过 `config/session.php` 的 `lifetime` 参数来调整
