### ISSUE TITLE
太他吗的难安装了

### ISSUE THREAD

**Issue by xsser** [4x99/code6#13]
一大堆报错。。。。。痛苦

PHP Warning:  require(/root/github/code6/vendor/autoload.php): failed to open stream: No such file or directory in /root/github/code6/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/root/github/code6/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /root/github/code6/artisan on line 18

**Comment by yoonper** [comment]
PHP + Laravel 部署确实稍显麻烦~
方便留个 QQ 帮你看下吗？

PS：近期会提供 Docker 方式部署

**Comment by xsser** [comment]
> PHP + Laravel 部署确实稍显麻烦~
> 方便留个 QQ 帮你看下吗？
> 
> PS：近期会提供 Docker 方式部署
