### ISSUE TITLE
提1个很实用的新需求

### ISSUE THREAD

**Issue by test502git** [4x99/code6#132]
公司体量比较大，对外的产品也非常多，目前的检测到的信息，大多数为官方自己公布的信息，并非真正的泄露，所以误报还会比较多
可以考虑优化1下白名单机制
如：链接\代码快照\仓库\用户名\等，  包含 xxx 就不通知，过滤掉 ，这个xxx是可以自己添加的

比如：一些代码中包含 “官方账号” 等字样 ，就过滤掉

**Comment by yoonper** [comment]
过滤代码中包含 “官方账号“ 的记录可以使用 NOT 关键字，如 “关键字 NOT 官方账号”
用户名、仓库名白名单现在已经有了，下个版本可能会加强，支持配置通配符

**Comment by test502git** [comment]
好的，在哪配置

**Comment by yoonper** [comment]
扫描配置 - 关键字支持高级语法

**Comment by yoonper** [comment]
用户名及仓库名自 v1.5.4 版本起支持通配符
