### ISSUE TITLE
任务配置页面下次扫描时间一直更新，最近扫描时间一直无变化是怎么回事呀？

### ISSUE THREAD

**Issue by skr-rks** [4x99/code6#133]
![任务配置页面](https://user-images.githubusercontent.com/57212526/123611432-2d9b8d00-d834-11eb-9219-f830359ebd11.png)

**Comment by yoonper** [comment]
似乎任务调度有问题
Cron 配置了吗

**Comment by skr-rks** [comment]
在哪里配置呀？

**Comment by skr-rks** [comment]
是指定时时间吗？

**Comment by yoonper** [comment]
如果是 Docker 部署，默认是配置好了的，没有启动任务检查一下 Cron 是否正常工作
如果是源码部署，参考：[源码部署 - 配置任务调度](https://github.com/4x99/code6/blob/master/doc/deploy-source.md#配置任务调度)

**Comment by skr-rks** [comment]
我是docker部署的。请问查看core是否正常需要看哪个log呢？

**Comment by yoonper** [comment]
Cron 每分钟启动，然后剩下的任务由框架调度
只要 `/storage/logs` 下的任一日志有更新，应该就是有正常工作

**Comment by skr-rks** [comment]
logs下的四个log文件都实时更新的。。那这个扫描任务是否在进行呀，这个最近扫描时间一直无变化

**Comment by yoonper** [comment]
可能没有正常工作，麻烦提供一下近期 `code6-*.log`、`job-run-*.log`  日志

**Comment by skr-rks** [comment]
[job-run-2021-06-28.log](https://github.com/4x99/code6/files/6725202/job-run-2021-06-28.log)
[code6-2021-06-28.log](https://github.com/4x99/code6/files/6725227/code6-2021-06-28.log)

**Comment by yoonper** [comment]
升级到 1.5.3 的时候新数据表没有导入，执行下面命令就可以了：
```
php artisan migrate --force
```

**Comment by skr-rks** [comment]
执行了还是不行。

**Comment by yoonper** [comment]
执行完后数据库应该有一张 config_common 表，看下是否存在

**Comment by skr-rks** [comment]
存在该表。内容为
mysql> select * from config_common;
+----+----------------+-------+
| id | key            | value |
+----+----------------+-------+
|  1 | whitelist_file | []    |

**Comment by yoonper** [comment]
已解决，未到任务启动时间。
