### ISSUE TITLE
扫描不启动

### ISSUE THREAD

**Issue by 98Kstar** [4x99/code6#135]
师傅您好，我按照您的docker要求配置成功之后，按此新建了扫描项目：
![image](https://user-images.githubusercontent.com/41816999/123891633-c7298280-d98b-11eb-93eb-73520348a1f1.png)
但是发现扫描并没有启动，他的最近扫描时间永远是空的，也没有任何东西扫描出来，
![image](https://user-images.githubusercontent.com/41816999/123891775-ffc95c00-d98b-11eb-9864-5a600b37ae0c.png)

不知道我应该直接就是填写关键字还是需要填写github的搜索语法

**Comment by yoonper** [comment]
麻烦参考 #133
如果无法解决告知一下是 Docker 部署还是源码部署，再把 `storage/logs` 日志发上来

**Comment by 98Kstar** [comment]
师傅您好，第一行就写了是按您docker要求配置部署的。storage/logs下文件是空的
![image](https://user-images.githubusercontent.com/41816999/123892568-6b5ff900-d98d-11eb-94cb-d3de1c81a13f.png)

**Comment by yoonper** [comment]
不好意思，刚刚没看到
日志是空的大概率是 CRON 服务没有正常启动，你可以检查一下
或者重新启个容器

**Comment by 98Kstar** [comment]
好的，谢谢师傅。
