### ISSUE TITLE
创建容器的时候，拒绝对资源的访问请求

### ISSUE THREAD

**Issue by barkosHuang** [4x99/code6#137]
1.我查了我的IP，正常访问数据库
![image](https://user-images.githubusercontent.com/52743072/125737674-c637ed51-7431-4e26-9247-15a9234de0f0.png)
2.启动容器（宿主机映射端口 666 与 MySQL 连接参数请根据情况修改，容器启动将自动连接 MySQL 并导入数据表）
![image](https://user-images.githubusercontent.com/52743072/125737817-9b61f5e8-c644-4a94-832f-cfc659425a8d.png)
3.选择三个任意一个镜像都报错；
![image](https://user-images.githubusercontent.com/52743072/125737902-d0d5806d-0f01-478d-8ec2-e46909f2c2bf.png)
![image](https://user-images.githubusercontent.com/52743072/125738028-aee7ff28-d42f-4918-bc0e-c027bf6ee95d.png)
![image](https://user-images.githubusercontent.com/52743072/125738078-a338af7c-0b2d-4478-851b-6b7940ff579c.png)
![image](https://user-images.githubusercontent.com/52743072/125738114-a0b76b22-0d89-4973-98b4-f49fc51c7bac.png)

接下来不知道如何创建容器，请麻烦帮忙解答；非常感谢

**Comment by yoonper** [comment]
https://github.com/4x99/code6/blob/master/doc/deploy-docker.md
参考文档，先 `build` 再启动容器，如果无法 `pull` 配置一下容器国内镜像加速：
```
vim /etc/containers/registries.conf
```

```
unqualified-search-registries = ["docker.io"]
[[registry]]
prefix = "docker.io"
location = "申请的ID.mirror.aliyuncs.com"
```

**Comment by barkosHuang** [comment]
已经build完毕，就是启动容器的时候出错。
申请的ID是指哪个ID 呢

**Comment by yoonper** [comment]
阿里云 - 容器镜像服务 - 镜像加速器
开通之后会有一个特定的 ID，或者用其他家镜像也是可以的

**Comment by yoonper** [comment]
似乎是你在 build 环节就有问题，执行 `podman images` 看看是否有：
```
REPOSITORY             TAG         IMAGE ID      CREATED         SIZE
localhost/code6        latest      cada30eaf829  43 minutes ago  600 MB
docker.io/library/php  7.4-apache  378760e3f7c7  13 days ago     423 MB
```

**Comment by barkosHuang** [comment]
我现在的镜像有这些
![image](https://user-images.githubusercontent.com/52743072/125746796-8482a231-ec11-49e2-a894-9de06e17e751.png)

**Comment by yoonper** [comment]
build 没有成功，成功的话应该会有一个 `localhost/code6`

**Comment by barkosHuang** [comment]
是我使用Dockerfile 创建镜像的时候这一步出错吗

**Comment by yoonper** [comment]
嗯

**Comment by barkosHuang** [comment]
非常感谢，已经解决了
