### ISSUE TITLE
如何重启服务

### ISSUE THREAD

**Issue by barkosHuang** [4x99/code6#138]
1.我在源码上修改文字描述的提示信息；方便理解
2.然后我重启了容器，无生效
3.请问如何重启生效我修改的文字描述呢

**Comment by yoonper** [comment]
容器内修改代码直接生效，不需要重启容器
重启容器 Dockerfile 会把 git clone 的代码复制到容器内（当然了，你也可以在容器外修改代码再启动容器）

**Comment by barkosHuang** [comment]
我是在容器外修改的，然后再启动的；
![image](https://user-images.githubusercontent.com/52743072/125773249-e44320f0-5056-4a49-aa27-bda0c92c81d1.png)
z
在git  clone 的目录下修改的，是不是在这修改了还需要创建images;
在容器内是如何修改的

**Comment by yoonper** [comment]
修改了需要创建 image
在容器修改的话直接进入容器 `docker exec -it code6-server /bin/bash` （podman 自行修改）

**Comment by barkosHuang** [comment]
我重启了docker ，docker inspect mysqld | grep IPAddress ，其中IPAddress 的IP 已经变化了，由原来的IP 172.16.0.3 变成了172.16.0.8  这个时候要怎么修改IP 呢

**Comment by yoonper** [comment]
进入容器修改 .env 文件

**Comment by barkosHuang** [comment]
第一次完docker ，不知道.env文件是在哪修改的呢？具体的路径是？
非常感谢你的耐心解答。

**Comment by yoonper** [comment]
`docker exec -it code6-server /bin/bash`
.env 在根目录

**Comment by barkosHuang** [comment]
感谢
