### ISSUE TITLE
宝塔源代码安装问题

### ISSUE THREAD

**Issue by NuyOahIII** [4x99/code6#139]
目前遇到的情况是所有的步骤都走了一遍了，然后宝塔会自动禁止使用../跳转目录，我修改设置以后不再报错，进入登录界面后一片空白
端口我使用的是55555

**Comment by yoonper** [comment]
请编辑项目根目录 `.env` 文件，将 `APP_DEBUG` 设置为 `true`，`APP_ENV` 设置为 `local`，然后再登录，看是否有报错。
或者提供 `storage/logs` 下的日志信息

**Comment by NuyOahIII** [comment]
感谢大佬回复，登录问题已经解决，原因是宝塔建站是统一使用www用户，需要给storage目录设置权限。

**Comment by yoonper** [comment]
ok

**Comment by NuyOahIII** [comment]
出现了一个新的问题，我的
![image](https://user-images.githubusercontent.com/61104521/126633329-46064104-e850-48cb-ac21-89f05b6f83ce.png)
![image](https://user-images.githubusercontent.com/61104521/126633391-0fefc5c7-7ea7-4239-bd41-98df60aa6da9.png)
令牌和任务都已经配置了但是无法进行自动扫描，希望能增加一个手动点击后扫描的功能

**Comment by yoonper** [comment]
自动扫描需要配置一个 Cron，请参考部署文档

因为码小六需要调度令牌配额，所有任务需放入队列依次执行
即便加入 “手动执行” 也不会实时立即执行，有此需求可以临时将扫描间隔改为 1 分钟
