### ISSUE TITLE
启动容器一直连不上数据库，数据库ip已经指定，还是不行，麻烦看下，谢谢

### ISSUE THREAD

**Issue by AlittleNobody** [4x99/code6#149]
1、[root@localhost code6]# docker logs -f 8dd6d0a341e3
Application key set successfully.

In Connection.php line 671:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
  chema.tables where table_schema = code6 and table_name = migrations and tab  
  le_type = 'BASE TABLE')                                                      
                                                                               

In Connector.php line 70:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

Starting periodic command scheduler: cron.
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
Starting Apache httpd web server: apache2.

2、root@8dd6d0a341e3:/var/www/html#  php artisan code6:user-list

In Connection.php line 671:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select `email` from `user`)  
                                                                               

In Connector.php line 70:
                                             
  SQLSTATE[HY000] [2002] Connection refused

**Comment by yoonper** [comment]
请看置顶 issue #1
