### ISSUE TITLE
邮件告警报错？

### ISSUE THREAD

**Issue by Byc4i** [4x99/code6#150]
请问这是什么问题，
![image](https://user-images.githubusercontent.com/18072317/128115863-bc1d433a-6fcc-447a-ad11-c58968f5367b.png)

**Comment by yoonper** [comment]
邮件通知启用了 SSL 协议，端口通常为 `465` 而非 `25`，在端口输入框 tooltip 有相关提示

**Comment by Byc4i** [comment]
该报错就是在配置465端口的适合产生的。0.0

**Comment by yoonper** [comment]
确认一下邮箱是否支持 SSL，也可以用第三方邮件客户端连接试试
