### ISSUE TITLE
docker build -t code6 . 时报错

### ISSUE THREAD

**Issue by rsyczx** [4x99/code6#152]
在拉取源码后，在目录下构建docker镜像时老是出错，换了好几台机器
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zlib1g-dev : Depends: zlib1g (= 1:1.2.11.dfsg-1) but 1:1.2.11.dfsg-2 is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y zip cron vim zlib1g-dev=1:1.2.11.dfsg-1 libpng-dev' returned a non-zero code: 100
安装不上默认的版本，就把 zlib1g 指定版本号，还是报错
apt-get update && apt-get install -y zip cron vim **zlib1g=1:1.2.11.dfsg-1** zlib1g-dev libpng-dev
E: Packages were downgraded and -y was used without --allow-downgrades.

按照报错提示修改为将 Dockerfile 文件修改为：
RUN apt-get update && apt-get install -y **--allow-downgrades** zip cron vim zlib1g=1:1.2.11.dfsg-1 zlib1g-dev libpng-dev
问题解决

**Comment by yoonper** [comment]
我下午测试一下看能否复现

**Comment by yoonper** [comment]
已复现，Docker 基础镜像更新导致
处理中。。

**Comment by yoonper** [comment]
已发布 1.5.5 版本修复该问题，感谢反馈！
