### ISSUE TITLE
docker环境部署

### ISSUE THREAD

**Issue by RoziSec** [4x99/code6#158]
有没有详细一点的docker环境部署教程啊，老是报各种错

**Comment by yoonper** [comment]
README.md 有 Docker 部署文档链接，如果报错无法解决可以提交 issue，贴上报错信息。

**Comment by RoziSec** [comment]
> README.md 有 Docker 部署文档链接，如果报错无法解决可以提交 issue，贴上报错信息。

谢谢回答，已经解决了。是我这边的mysql授权没有弄好的原因

**Comment by RoziSec** [comment]
同时满足两个关键字的，要怎么写关键字呢？用AND查询出来的跟自己手动查的结果不太一样

**Comment by yoonper** [comment]
因为 GitHub 使用了 ES 作为查询引擎，查询前如果有特殊字符有可能被分词
可以使用 `https://github.com/search?o=desc&q=关键词&s=indexed&type=Code` 测试查询结果

**Comment by RoziSec** [comment]
> 因为 GitHub 使用了 ES 作为查询引擎，查询前如果有特殊字符有可能被分词
> 可以使用 `https://github.com/search?o=desc&q=关键词&s=indexed&type=Code` 测试查询结果

好的。感谢解答
