### ISSUE TITLE
需求：自定义扫描时间

### ISSUE THREAD

**Issue by tattooweb** [4x99/code6#159]
希望可以自定义扫描时间和钉钉通知的时间，精确到年月日时分秒，谢谢

**Comment by yoonper** [comment]
能说明一下使用场景吗

**Comment by tattooweb** [comment]
> 
> 
> 能说明一下使用场景吗

编辑任务的扫描间隔，这个功能感觉不太清晰。我设置了扫描间隔10000+分钟，但是扫描时间还是在第二天。我需要每周五晚定时开始扫描，每个关键字都在不同时间进行，然后每周一钉钉发送通知，能自定义时间而不是间隔就好了，感谢

**Comment by yoonper** [comment]
任务启动时间 = 当前分钟时间戳 % (扫描间隔 * 60)，余数为 0
