### ISSUE TITLE
创建用户时报错

### ISSUE THREAD

**Issue by xuxiaofan1101** [4x99/code6#160]
In Connection.php line 671:
                                                                                 
  SQLSTATE[HY000] [2002] Connection timed out (SQL: select `email` from `user`)  
                                                                                 

In Connector.php line 70:
                                               
  SQLSTATE[HY000] [2002] Connection timed out  
                                               
请问下这个报错怎么解决呀。telnet mysql的端口是通的，账号密码也是对的

**Comment by yoonper** [comment]
`MYSQL_HOST` 值设置的是什么，如果 MySQL 在宿主机，IP 一般是 `172` 开头，可在宿主机执行 `ifconfig` 或 `ip addr` 查看 `docker0` 的 IP
