### ISSUE TITLE
使用php artisan code6:user-add <邮箱> <密码>　　报错

### ISSUE THREAD

**Issue by barkosHuang** [4x99/code6#161]
我已经部署了，可以访问
但在创建用户时出错，可能是数据库的问题，麻烦帮忙定位是什么问题呢？
![image](https://user-images.githubusercontent.com/52743072/134799116-f0135e3f-c6d8-4693-b040-5fca5270d527.png)

**Comment by yoonper** [comment]
确认一下是否能正常连接数据库，参考置顶 issue #1 第一点

**Comment by barkosHuang** [comment]
![image](https://user-images.githubusercontent.com/52743072/134805092-dbeed04e-13ee-4c21-b954-f9b22eec8bc8.png)
请问这个创建这个库是code6 吗。要如何授权呢

**Comment by yoonper** [comment]
是的，码小六会自动创建数据表，授权请看置顶常见问题 1。

**Comment by barkosHuang** [comment]
![image](https://user-images.githubusercontent.com/52743072/134805900-841e4599-25c9-40dc-a1ef-edfed6046d39.png)
![image](https://user-images.githubusercontent.com/52743072/134805906-76927ccb-a9b6-4837-b853-00c68fef7ecd.png)
![image](https://user-images.githubusercontent.com/52743072/134805915-5acb17b3-c0d7-48fe-872b-2f453284c604.png)
当前容器执行 php artisan migrate 导入数据表，还是出错了

**Comment by barkosHuang** [comment]
IP 怎么变成 172.17.03 的呢

**Comment by yoonper** [comment]
你确定改的是 docker 容器里的配置文件吗

**Comment by barkosHuang** [comment]
改过根目录的.env文件的地址

**Comment by barkosHuang** [comment]
![image](https://user-images.githubusercontent.com/52743072/134806357-8cdea125-a9be-4304-88a7-688493654fd3.png)
执行php artisan code6:user-add，报的错误

**Comment by yoonper** [comment]
如果实际 ip 是 .2 配置是 .3 重新启动一个容器试试
ip 没错，access denied 参考常见问题 1
