### ISSUE TITLE
docker build -t code6 . 安装php拓展时报错

### ISSUE THREAD

**Issue by Tkid3** [4x99/code6#162]
环境：
centos7.5，Docker version 18.09.6, build 481bc77156

报错信息：
`Step 15/32 : RUN docker-php-ext-install pdo_mysql
 ---> Running in fb17fcbd996f
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
The command '/bin/sh -c docker-php-ext-install pdo_mysql' returned a non-zero code: 2`

执行到第15步报错。
1.查看宿主机selinux是关闭的
2.构建时注释掉15以及之后的，启动容器后执行docker-php-ext-install pdo_mysql是可以成功的

**Comment by GallopYD** [comment]
排查处理中...

**Comment by GallopYD** [comment]
实测 Docker 版本18.09.6，安装 PHP 7.3 以上版本的 PHP 扩展会报错，
码小六运行环境是 PHP 7.4，所以安装 PHP 扩展时会出现以上报错，

实测 Docker 19.xx.x、20.xx.x 版本安装正常，请更新 Docker 版本后再进行安装。

**Comment by Tkid3** [comment]
是的，昨天无意间升级到20.10.8，问题就没有了。谢谢~
