### ISSUE TITLE
建议增加文件类型过滤的选项，可以自己设定监测的文件类型

### ISSUE THREAD

**Issue by mx208223763** [4x99/code6#163]
建议增加增加类型，可以自行设定文件的类型，会方便一些
![image](https://user-images.githubusercontent.com/91749786/135803562-c485dd9a-ebbf-43bb-bf71-deb17eee6099.png)
![image](https://user-images.githubusercontent.com/91749786/135803600-0ceeed87-fddd-4e57-a390-99a828b7b5f7.png)

**Comment by yoonper** [comment]
可以在扫描关键字中进行配置，如 `xxx language:yml`
参考文档：https://docs.github.com/en/rest/reference/search

**Comment by yoonper** [comment]
下一版本会在 “任务配置” - “关键字说明” 中增加相关提示，感谢建议！
