### ISSUE TITLE
创建镜像后，无法通过浏览器访问系统

### ISSUE THREAD

**Issue by zhongjiao01** [4x99/code6#164]
通过docker安装后，用户可以创建，但是无法通过浏览器访问到系统，在服务器查看映射端口处于监听状态，这是怎么回事呢

**Comment by yoonper** [comment]
请依次排查一下是在哪个环节无法访问
1. Docker 容器中 `curl 0.0.0.0`
2. 宿主机 `curl 0.0.0.0:666`

如果均可访问而浏览器无法访问，多半是宿主机防火墙未开放端口

**Comment by zhongjiao01** [comment]
我找到原因了，是因为docker中的apacha2启动时加载mpm失败导致的，现在还在找解决办法，大佬有好的办法吗

**Comment by yoonper** [comment]
没有复现，如果临时使用可以进入容器关闭 Apache，然后使用 PHP 自带的 Web 服务：
```
export PHP_CLI_SERVER_WORKERS=24
nohup php artisan serve --host 0.0.0.0 --port=80 &
```

线上生产环境还是建议使用 Apache
