### ISSUE TITLE
邮箱告警配置报错

### ISSUE THREAD

**Issue by tsoham** [4x99/code6#166]
![image](https://user-images.githubusercontent.com/86467130/137313253-805c7eb0-4fd4-4f6f-bb33-b9707a68e38c.png)
![image](https://user-images.githubusercontent.com/86467130/137313391-1d8b91c2-b50c-444e-9c9f-42c302411f8b.png)

请问这是什么问题，邮件客户端测试支持ssl

**Comment by yoonper** [comment]
请参考 #150

**Comment by tsoham** [comment]
这两个应该是一样的问题。暂时没有找到原因。

**Comment by yoonper** [comment]
邮局支持的话使用 465 端口即可

**Comment by tsoham** [comment]
解决了。
php里没有邮箱服务器的根证书，需要添加到信任列表里去。
openssl默认路径位置： php -r "print_r(openssl_get_cert_locations());"
添加到default_cert_file 对应的这一行路径
