### ISSUE TITLE
增加过滤

### ISSUE THREAD

**Issue by test502git** [4x99/code6#173]
目前已经可以过滤后缀名了，希望增加 过滤掉 make down 类型信息

**Comment by yoonper** [comment]
不好意思，漏看了 issue
可以设置搜索关键字：`关键字 NOT language:markdown`

**Comment by test502git** [comment]
关键字 NOT language:markdown  请问如此设置？

**Comment by test502git** [comment]
关键字 NOT language:markdown 请问如何 设置？

**Comment by yoonper** [comment]
[ 任务配置 ] 模块，搜索关键字直接填上就行
