### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by barkosHuang** [4x99/code6#174]
访问数据库被拒绝的时候，是不是要授权呢？
确认 MySQL 是否已给 MYSQL_USERNAME 用户授权，授权命令：GRANT ALL PRIVILEGES ON *.* to <MYSQL_USERNAME>@'%' identified by '<password>';（请根据实际情况授权）
请问这个给用户授权是进入到docker mysql 里面去授权吗，授权命令是在哪个地方执行的呢？
![image](https://user-images.githubusercontent.com/52743072/142970815-7bbeee53-d2b7-4139-b6b3-03a342a608e1.png)

**Comment by yoonper** [comment]
登录 MySQL 后执行 SQL 命令授权

**Comment by barkosHuang** [comment]
我按照常见问题一的步骤执行后；还是出错；
![image](https://user-images.githubusercontent.com/52743072/143019259-9b1029b3-f6ea-4216-b919-590abf16462c.png)
我未进入到docker 容器内，是可以访问mysql 的；可以帮忙看看这上面报的是什么错误吗

**Comment by yoonper** [comment]
数据库不存在，手动创建数据库，删除当然容器，重新启动一个容器，启动时会自动导入数据表。
