### ISSUE TITLE
ls: cannot access '.': Operation not permitted configure: error: working directory cannot be determined

### ISSUE THREAD

**Issue by u-raison** [4x99/code6#175]
Step 14/32 : RUN rm -rf /var/lib/apt/lists/* && apt-get clean
 ---> Running in 8e61a5a0e32a
Removing intermediate container 8e61a5a0e32a
 ---> 22ae0973e332
Step 15/32 : RUN docker-php-ext-install pdo_mysql
 ---> Running in 0027ea4fa74e
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
**ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined**
The command '/bin/sh -c docker-php-ext-install pdo_mysql' returned a non-zero code: 2

docker build 的时候出现这个错误  centos7

**Comment by yoonper** [comment]
稍等我测试一下

**Comment by u-raison** [comment]
> 

回复的好快啊。

docker -v
Docker version 18.06.3-ce, build d7080c1

**Comment by yoonper** [comment]
升级 Docker 到 20+ 版本试试

**Comment by u-raison** [comment]
> 

完美解决，另外为什么有时候告警邮件，只有一条审计记录得时候，会连续发送4封一样的邮件?

另外提个需求： 钉钉通知的时候是否可以把关键字、仓库名、文件路径也打印一下，这样好在手机上先查看一下。

**Comment by yoonper** [comment]
重复发送邮件的问题稍后排查一下
告警通知主要考虑到有时候记录特别多，会超出某些通知渠道接口的长度限制，目前可以通过移动版查看

**Comment by test502git** [comment]
> > 
> 
> 回复的好快啊。
> 
> docker -v Docker version 18.06.3-ce, build d7080c1

确实确实~
