### ISSUE TITLE
优化监控cnnvd漏洞库？

### ISSUE THREAD

**Issue by barkosHuang** [4x99/code6#176]
发现一个新需求：通过关键词监控cnnvd 漏洞库，发现关于与关键词相关的漏洞，及时告警。

**Comment by yoonper** [comment]
感谢建议！我们会讨论一下

**Comment by barkosHuang** [comment]
你好，我在app/services/NotifyServices.php 上修改了消息模板，想增加几行描述文本，一直都修改不成功，想问在原有的基础上要如何修改呢/

**Comment by yoonper** [comment]
通知配置页面就可以直接配置，不用修改代码。

**Comment by barkosHuang** [comment]
消息通知
关键词：
论坛名称：
论坛链接：
点赞数：
浏览量：
评论数：
我想改成这个格式的。
可是这段代码好像不支持
![image](https://user-images.githubusercontent.com/52743072/147344706-33bbe247-1606-422f-9cfe-f229139ce95a.png)

**Comment by barkosHuang** [comment]
内容是固定的，就是想调整上面的格式。

**Comment by yoonper** [comment]
点赞数 浏览量等参数码小六是没有的

**Comment by barkosHuang** [comment]
我知道哈，我想在你原有消息通知模板上增加，（点赞数浏览数，我以及封装好了），就是想问一下在NotifyServices.php, 上如何修改原有的模板，变成上面的模板呢

**Comment by yoonper** [comment]
/app/Console/Commands/NotifyCommand.php 第 86 行
