### ISSUE TITLE
docker部署报错，提示apache2启动失败

### ISSUE THREAD

**Issue by GitHubcaowei** [4x99/code6#179]
**容器启动报错信息如图：**
![image](https://user-images.githubusercontent.com/35019319/150621295-7127a05b-d217-4a38-9c3e-06ecbd73a8aa.png)

**服务器环境是centos7，httpd的版本原先是2.4.6，也报上述错误，然后将httpd升级到2.4.53.还是报一样的错，httpd的error_log如下：**

![image](https://user-images.githubusercontent.com/35019319/150621371-6b7ca4eb-aa86-4bd9-b5a1-43c50e1f66be.png)

**请问是什么原因？如何解决？**

**Comment by GitHubcaowei** [comment]
网上有说php.ini加载一些没用的dll

**Comment by yoonper** [comment]
可能是宿主机 Kernel 版本较低引起的
运行一下 `yum update` 或者升级 Kernel 版本试试

**Comment by cshenger** [comment]
> 可能是宿主机 Kernel 版本较低引起的 运行一下 `yum update` 或者升级 Kernel 版本试试

yum update后没效果，然后我换台内核更高的服务器就可以了，谢谢大佬

**Comment by GitHubcaowei** [comment]
> yum update

解决了，yum update没效果，然后我换了个内核更高的服务器就可以了，谢谢大佬
