### ISSUE TITLE
docker部署已经配置好了数据库用户并授权，仍然在php artisan code6:user-add <邮箱> <密码>

### ISSUE THREAD

**Issue by baihuhao2007** [4x99/code6#181]
docker部署已经配置好了数据库用户并授权，仍然在php artisan code6:user-add <邮箱> <密码>报错

![image](https://user-images.githubusercontent.com/79696420/154031022-5602c2f7-1078-4e94-a352-15cf01db7d4d.png)
![image](https://user-images.githubusercontent.com/79696420/154031068-3ee7c87b-8062-4c66-8820-64b5b6fd06d6.png)

**Comment by yoonper** [comment]
无法连接数据库，请参考置顶 “常见问题” #1 解决
