### ISSUE TITLE
已经成功添加用户，且正确配置了ip地址，但是无法访问页面

### ISSUE THREAD

**Issue by baihuhao2007** [4x99/code6#182]
报错：无法访问此网站

**Comment by yoonper** [comment]
麻烦提供更详细的信息，比如安装方式、日志、故障提示等

**Comment by baihuhao2007** [comment]
使用linux安装的，我看日志好像是连接数据库的问题，但是我都已经创建用户了不应该是连接的问题吧
![2757c206a2b7ab0b70a8dfd628d3dcd](https://user-images.githubusercontent.com/79696420/154654312-4e74733e-40fa-4b29-83d5-ec9aa5f339eb.png)
![99b9a78619b23429a76026e320ed603](https://user-images.githubusercontent.com/79696420/154654328-abdb722e-988a-4b9b-b674-9191faabb295.png)

**Comment by yoonper** [comment]
目录 `storage/logs` 下有报错日志吗？
源码安装容易出现一个问题，cron 任务是 root 用户，往 `storage/logs` 写日志后，web 是非 root 用户，无权写日志导致报错

**Comment by baihuhao2007** [comment]
这个目录下是空的，没有文件，请问您有联系方式吗，快交流起来会方便一点

**Comment by yoonper** [comment]
QQ：50663950

**Comment by baihuhao2007** [comment]
加您了

**Comment by yoonper** [comment]
iptables 问题，已解决
