### ISSUE TITLE
任务配置处可否加一个批量删除任务的功能

### ISSUE THREAD

**Issue by linluhaijing** [4x99/code6#194]
任务配置处可否加一个批量删除任务的功能

**Comment by yoonper** [comment]
可以，下一个版本增加

**Comment by linluhaijing** [comment]
任务下发的时候通常是关键字+域名这种，能加一个功能是  关键字遍历+域名不变嘛

**Comment by yoonper** [comment]
每个用户需求不一样，这个暂时只能通过添加关键字来解决
除非有一个比较好且大众容易理解的交互方式

**Comment by yoonper** [comment]
v1.6.0 已增加此功能
