### ISSUE TITLE
docker-compose部署出现问题

### ISSUE THREAD

**Issue by linsihao7788** [4x99/code6#199]
## 安装方式
docker-compose部署

## 问题描述
docker-compose --env-file .env.docker-compose up -d --build 出现错误

## 运行环境
docker -v
Docker version 20.10.14+dfsg1, build a224086
docker-compose -v
docker-compose version 1.29.2, build unknown

[ 环境检查 ]
PHP 版本: 8.1.5  
PDO 扩展: 已安装  
Laravel 密钥: 未生成  请执行命令 php artisan key:generate 生成密钥
Storage 目录: 可读写  
Composer Package: 未导入  请安装 Composer 并执行 composer install 安装包
MySQL 连接: 失败  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for  failed: Name or service not known
MySQL 数据表: 未导入  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for  failed: Name or service not known

## 报错情况
![企业微信截图_16558877933498](https://user-images.githubusercontent.com/46431972/174988440-964b8737-22f2-42b9-9a2d-e621327cf0d1.png)
![企业微信截图_16558878091393](https://user-images.githubusercontent.com/46431972/174988466-57798582-8bc7-4778-aab4-f53c9d21ed43.png)
![企业微信截图_16558878299865](https://user-images.githubusercontent.com/46431972/174988481-62f301f2-6c18-4dfb-aaf0-3f019857a895.png)

**Comment by linsihao7788** [comment]
昨天部署的时候还没试，今天换了个虚拟机部署就有问题了

**Comment by yoonper** [comment]
宿主机配置一下 Docker DNS 试试：
```
vim /etc/docker/daemon.json
```
```
{                                                                          
    "dns": ["223.5.5.5", "8.8.8.8"]                                                                           
}
```

**Comment by linsihao7788** [comment]
可以了，谢谢大佬，是网络的问题
