### ISSUE TITLE
请问能提供一份nginx对应的重定向规则吗？

### ISSUE THREAD

**Issue by wjf2016** [4x99/code6#20]
你好，请问能提供一份nginx对应的重定向规则吗？

**Comment by yoonper** [comment]
码小六是基于 Laravel 框架开发，你搜索一下 Laravel Nginx 配置，应该是通用的。

PS：过几天会发布支持 Docker 部署

**Comment by yoonper** [comment]
https://laravel.com/docs/7.x/deployment#nginx
