### ISSUE TITLE
程序17号之后就没有再执行任务扫描了

### ISSUE THREAD

**Issue by zoombegod** [4x99/code6#200]
## 安装方式
Docker 安装

## 问题描述
程序17号之后就没有再执行任务扫描了,之前一直使用正常,后来17号加入了docker restart db3a5cd48a2f 晚上10点半定期执行 ,之后再也
没有扫描过了
## 运行环境
root@db3a5cd48a2f:/var/www/html# php doctor.php

--------------------------------------------------------------------------------
[ 环境检查 ]
PHP 版本: 7.4.28
PDO 扩展: 已安装
Laravel 密钥: 已生成
Storage 目录: 可读写
Composer Package: 已导入
MySQL 连接: 成功
MySQL 数据表: 已导入
--------------------------------------------------------------------------------
[ 其他信息 ]
码小六版本：1.5.6
框架运行环境：production
框架调试开关：false
PHP 禁用函数：无
PHP 已编译模块：Core,date,libxml,openssl,pcre,sqlite3,zlib,ctype,curl,dom,fileinfo,filter,ftp,hash,iconv,json,mbstring,SPL,PDO,pdo_sqlite,session,posix,readline,Reflection,standard,SimpleXML,Phar,tokenizer,xml,xmlreader,xmlwriter,mysqlnd,gd,pdo_mysql,sodium
--------------------------------------------------------------------------------

有任何问题和建议请联系-> https://github.com/4x99/code6/issues

## 报错日志
日志目录：`storage/logs`
root@db3a5cd48a2f:/var/www/html/storage/logs# ll
total 47676
-rwxr-xr-x 1 www-data www-data    1116 Jun 11 17:05 code6-2022-06-11.log
-rwxr-xr-x 1 www-data www-data     868 Jun 12 23:44 code6-2022-06-12.log
-rwxr-xr-x 1 www-data www-data    1364 Jun 13 22:58 code6-2022-06-13.log
-rwxr-xr-x 1 www-data www-data    1919 Jun 14 22:47 code6-2022-06-14.log
-rwxr-xr-x 1 www-data www-data    1736 Jun 15 23:58 code6-2022-06-15.log
-rwxr-xr-x 1 www-data www-data   86123 Jun 16 23:49 code6-2022-06-16.log
-rwxr-xr-x 1 www-data www-data     248 Jun 17 02:51 code6-2022-06-17.log
-rwxr-xr-x 1 www-data www-data 3664782 Jun 19 23:59 job-add-2022-06-19.log
-rwxr-xr-x 1 www-data www-data 3949902 Jun 20 23:59 job-add-2022-06-20.log
-rwxr-xr-x 1 www-data www-data 4235022 Jun 21 23:59 job-add-2022-06-21.log
-rwxr-xr-x 1 www-data www-data 4520142 Jun 22 23:59 job-add-2022-06-22.log
-rwxr-xr-x 1 www-data www-data 4805262 Jun 23 23:59 job-add-2022-06-23.log
-rwxr-xr-x 1 www-data www-data 5090382 Jun 24 23:59 job-add-2022-06-24.log
-rwxr-xr-x 1 www-data www-data 1935648 Jun 25 08:42 job-add-2022-06-25.log
-rwxr-xr-x 1 www-data www-data  515021 Jun 11 23:59 job-run-2022-06-11.log
-rwxr-xr-x 1 www-data www-data  739008 Jun 12 23:59 job-run-2022-06-12.log
-rwxr-xr-x 1 www-data www-data  695899 Jun 13 23:59 job-run-2022-06-13.log
-rwxr-xr-x 1 www-data www-data  713511 Jun 14 23:59 job-run-2022-06-14.log
-rwxr-xr-x 1 www-data www-data  712010 Jun 15 23:59 job-run-2022-06-15.log
-rwxr-xr-x 1 www-data www-data  761047 Jun 16 23:59 job-run-2022-06-16.log
-rwxr-xr-x 1 www-data www-data   56778 Jun 17 03:30 job-run-2022-06-17.log
-rwxr-xr-x 1 www-data www-data      64 Jun 18 03:30 job-run-2022-06-18.log
-rwxr-xr-x 1 www-data www-data      64 Jun 19 03:30 job-run-2022-06-19.log
-rwxr-xr-x 1 www-data www-data     768 Jun 20 03:30 job-run-2022-06-20.log
-rwxr-xr-x 1 www-data www-data     128 Jun 21 03:30 job-run-2022-06-21.log
-rwxr-xr-x 1 www-data www-data     128 Jun 22 03:30 job-run-2022-06-22.log
-rwxr-xr-x 1 www-data www-data     128 Jun 23 03:30 job-run-2022-06-23.log
-rwxr-xr-x 1 www-data www-data      64 Jun 24 03:30 job-run-2022-06-24.log
-rwxr-xr-x 1 www-data www-data      64 Jun 25 03:30 job-run-2022-06-25.log
-rwxr-xr-x 1 www-data www-data 2091517 Jun 19 23:59 notify-2022-06-19.log
-rwxr-xr-x 1 www-data www-data 2254237 Jun 20 23:59 notify-2022-06-20.log
-rwxr-xr-x 1 www-data www-data 2416957 Jun 21 23:59 notify-2022-06-21.log
-rwxr-xr-x 1 www-data www-data 2579677 Jun 22 23:59 notify-2022-06-22.log
-rwxr-xr-x 1 www-data www-data 2742397 Jun 23 23:59 notify-2022-06-23.log
-rwxr-xr-x 1 www-data www-data 2905117 Jun 24 23:59 notify-2022-06-24.log
-rwxr-xr-x 1 www-data www-data 1104688 Jun 25 08:42 notify-2022-06-25.log

cat notify-2022-06-25.log

[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:22] production.INFO: Work done
[2022-06-25 09:06:23] production.INFO: Start notifying user
[2022-06-25 09:06:23] production.INFO: Work done
[2022-06-25 09:06:23] production.INFO: Start notifying user
[2022-06-25 09:06:23] production.INFO: Work done
[2022-06-25 09:06:23] production.INFO: Start notifying user
[2022-06-25 09:06:23] production.INFO: Work done

root@db3a5cd48a2f:/var/www/html/storage/logs# cat job-run-2022-06-25.log
[2022-06-25 03:30:16] production.INFO: Start running scan job

**Comment by yoonper** [comment]
已提供的信息无法定位问题
方便的话把 `2020-06-16` 之后的所有日志发给我看看 `yoonper@qq.com`

**Comment by zoombegod** [comment]
已发 感谢

**Comment by yoonper** [comment]
从日志看可能定时任务执行卡住，有很多任务同时在执行
建议重启一个容器，或者进入当前容器，把 PHP 相关的任务都 kill 了再观察下

**Comment by zoombegod** [comment]
PHP 相关的任务都怎么kill掉呢

**Comment by yoonper** [comment]
进入容器
ps -ef | grep php
看下 pid 再 kill

**Comment by zoombegod** [comment]
好的 我kill下看看

**Comment by zoombegod** [comment]
关闭定时restart容器的计划任务后 每天都会出现web服务无法访问的情况

该网页无法正常运作185.198.xxx.xxx 未发送任何数据。
ERR_EMPTY_RESPONSE


在主机上执行
root@vps90425:~# netstat -antp
发现端口是开放的
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      3936930/docker-prox

进入容器里面
执行ps -aux
root@db3a5cd48a2f:/var/www/html# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2404     8 ?        Ss   Jun25   0:01 /bin/sh -c /bin/bash docker-entrypoint.sh
root         7  0.0  0.0   3820     4 ?        S    Jun25   0:00 /bin/bash docker-entrypoint.sh
root        36  0.0  0.0   3668    64 ?        Ss   Jun25   0:06 /usr/sbin/cron
root        72  0.0  0.0   2348    36 ?        S    Jun25   0:21 tail -f /dev/null
root      7224  0.0  0.0   6040     0 ?        S    08:00   0:00 /usr/sbin/CRON
root      7241  0.0  0.0   2404     0 ?        Ss   08:00   0:00 /bin/sh -c cd /var/www/html && /usr/local/bin/php artisan schedule:run >> /dev/null 2>&1
root      7256  0.0  0.0  90664   300 ?        S    08:00   0:02 /usr/local/bin/php artisan schedule:run
root      7851  0.0  0.0   2404     0 ?        S    08:00   0:00 sh -c '/usr/local/bin/php' 'artisan' code6:job-run > '/dev/null' 2>&1
root      7852  0.7  1.5 185708 16384 ?        S    08:00   0:30 /usr/local/bin/php artisan code6:job-run
root     20389  0.2  0.2   4084  2364 pts/0    Ss   09:10   0:00 /bin/bash
root     21039  0.0  0.2   6684  2788 pts/0    R+   09:11   0:00 ps -aux


进程也是在的

**Comment by yoonper** [comment]
删掉容器，重新创建一个看是否正常

**Comment by zoombegod** [comment]
解决了 是内存不足导致任务卡死
