### ISSUE TITLE
一些细节的建议

### ISSUE THREAD

**Issue by zoombegod** [4x99/code6#201]
1.登陆界面能否添加密码错误的验证提醒
2.在扫描结果翻页里面能否在翻页之后,滑块处于最上面而不是最下面
3.有时候任务卡住了,能否添加清空待执行任务的功能
4.移动端,看扫描结果,点击任意一个扫描结果,跳转至github查完代码返回来,又得从第一页重新往后翻,有没有办法返回到原来那一页,并添加一个跳转到指定扫描结果页面数的输入框
5.能否添加一个查看正在执行的任务的进度查看框

**Comment by yoonper** [comment]
感谢反馈！
第 1 点登录应该是有提示 “邮箱或密码错误！” 吧，除非捕获到其他异常，可能会有其他异常提示
其他的我们会讨论一下

**Comment by Akityo** [comment]
顺带提一下，能不能设置扫描时间

因为GitHub token 配额重置有时间。

但是关键词加进去，全是同一个时间扫，而且迟了半小时再添加其他的，也还是同一个时间扫。 这样会导致同一时间扫描频率很高，导致超出配额。

**Comment by yoonper** [comment]
> 

码小六扫描的时候会把关键字任务加入队列，然后按队列顺序逐个扫描，这种方式能保证同一时间扫描任务只有一个，以便限制请求配额。

超出配额先确认一下令牌是否有在其他地方使用，正常描时会检查配额使用情况并切换至有配额的令牌，依旧不够建议通过增加令牌来解决。

**Comment by Akityo** [comment]
@yoonper 收到，感谢， 还有，消息通知模版，能支持代码片段吗，摘代码片段部分，支持发到通知消息。 目前是消息汇总，但是每次登陆也很麻烦，或者能不能提供无需登陆的url，以快速预览内容。

**Comment by yoonper** [comment]
> @yoonper 收到，感谢， 还有，消息通知模版，能支持代码片段吗，摘代码片段部分，支持发到通知消息。 目前是消息汇总，但是每次登陆也很麻烦，或者能不能提供无需登陆的url，以快速预览内容。

没有提供详细信息原因有几点：
1、正常流程需要对扫描记录进行审核，多人协同的时候，大家没有通过系统去操作，容易出现重复检查的问题
2、一些通知渠道字数有限制，有时候新增关键字，会一下扫描到大量结果
3、移动版应该会保留登录状态比较久，直接打开就能看

**Comment by yoonper** [comment]
第 4 点什么情况下会出现，我们没有复现，后退会回到原来所在页码

**Comment by L1NG0v0** [comment]
能提供API接口吗？需要集成到公司平台中去

**Comment by yoonper** [comment]
> 能提供API接口吗？需要集成到公司平台中去

具体需要哪些接口

**Comment by L1NG0v0** [comment]
> > 能提供API接口吗？需要集合到公司平台中去
> 
> 工具需要哪些接口

添加扫描任务的接口和展示结果的接口

**Comment by yoonper** [comment]
> > > 能提供API接口吗？需要集合到公司平台中去
> > 
> > 
> > 工具需要哪些接口
> 
> 添加扫描任务的接口和展示结果的接口

这个我们有考虑支持，但是可能没那么快，年后忙完有空余时间才能开发

**Comment by L1NG0v0** [comment]
> 



> > > > 能提供API接口吗？需要集合到公司平台中去
> > > 
> > > 
> > > 工具需要哪些接口
> > 
> > 
> > 添加扫描任务的接口和展示结果的接口
> 
> 这个我们有考虑支持，但是可能没那么快，年后忙完有空余时间才能开发

好的 感谢

**Comment by Ryang-230111** [comment]
考虑支持windows安装吗

**Comment by yoonper** [comment]
> 考虑支持windows安装吗

近期应该不会支持
