### ISSUE TITLE
钉钉通知

### ISSUE THREAD

**Issue by monikastudy** [4x99/code6#208]
钉钉通知测试没成功
机器人需要添加关键字

钉钉通知的截图有么

**Comment by yoonper** [comment]
默认可以设置关键字：码小六
也可以在 [ 通知配置 ] - 右上角 [ 通知模板 ] 配置消息内容，然后再根据消息内容设置钉钉的关键字

**Comment by monikastudy** [comment]
可以增加发现代码的提交时间么

**Comment by yoonper** [comment]
没记错的话，GitHub 没有提供代码提交时间

**Comment by monikastudy** [comment]
vipkid监控是有的

**Comment by yoonper** [comment]
回头我确认一下，感谢反馈
