### ISSUE TITLE
安全问题：扫描结果的【编辑信息】处有存储型XSS漏洞

### ISSUE THREAD

**Issue by ce-automne** [4x99/code6#221]
## 漏洞复现

登录码小六平台，在监控到的【扫描结果】里，分别选择 【操作】>>【编辑信息】，填入如下XSS Payload:
```
<img src=1 onerror=alert(document.cookie)>，xss test
```
![image](https://user-images.githubusercontent.com/20917372/189286428-4f7cc424-f6c1-4069-922c-6496f7178a28.png)

点击提交

随后访问【扫描结果】页面，将会触发存储型XSS漏洞，产生弹框。

![image](https://user-images.githubusercontent.com/20917372/189286295-2c4c2508-5685-4e1e-bb1f-12b0d5076326.png)

## 漏洞影响

执行Javascript脚本，攻击者能够以管理员或其他用户身份调用相关api接口

**Comment by yoonper** [comment]
感谢反馈！

**Comment by yoonper** [comment]
已修复，近期会发布新版本。
