### ISSUE TITLE
container for service "mysql" is unhealthy

### ISSUE THREAD

**Issue by wooyunwang** [4x99/code6#223]
## 安装方式
Docker-Compose 安装

## 问题描述
# MySQL 挂载到宿主机的目录
如果mysql是宿主机直接安装的话，这里的目录路径要填哪一个？

## 运行环境
[ 环境检查 ]
PHP 版本: 7.3.33-2+ubuntu18.04.1+deb.sury.org+1  
PDO 扩展: 已安装  
Laravel 密钥: 未生成  请执行命令 php artisan key:generate 生成密钥
Storage 目录: 可读写  
Composer Package: 未导入  请安装 Composer 并执行 composer install 安装包
MySQL 连接: 失败  could not find driver
MySQL 数据表: 未导入  could not find driver
--------------------------------------------------------------------------------
[ 其他信息 ]
码小六版本：1.6.1
框架运行环境：无
框架调试开关：无
PHP 禁用函数：无
PHP 已编译模块：Core,date,libxml,openssl,pcre,zlib,filter,hash,pcntl,Reflection,SPL,sodium,session,standard,PDO,calendar,ctype,exif,fileinfo,ftp,gettext,iconv,json,Phar,posix,readline,shmop,sockets,sysvmsg,sysvsem,sysvshm,tokenizer,Zend OPcache
--------------------------------------------------------------------------------

## 报错日志
敲入启动容器的命令时 出现 container for service "mysql" is unhealthy

**Comment by yoonper** [comment]
目前已知 MYSQL_USER 为 root 时会出现这个问题，下一版本会添加相关提示
如果不是此原因请用 docker logs 命令查看 mysql 容器的日志

**Comment by wooyunwang** [comment]
修改了.env.docker-compose环境配置文件里面的MYSQL用户名称，不再是root了，依然是相同的报错

**Comment by yoonper** [comment]
请用 docker logs 命令查看 mysql 容器的日志

**Comment by wooyunwang** [comment]
找到原因了，是宿主机原先安装了一个mysql，存放数据的默认路径跟docker冲突了。现在问题解决。
