### ISSUE TITLE
docker里面的php缺少插件报错

### ISSUE THREAD

**Issue by wooyunwang** [4x99/code6#224]
## 安装方式
Docker-Compose 安装

## 问题描述
docker里面的php缺少gd插件报错

## 运行环境
[ 环境检查 ]
PHP 版本: 7.3.33-2+ubuntu18.04.1+deb.sury.org+1  
PDO 扩展: 已安装  
Laravel 密钥: 未生成  请执行命令 php artisan key:generate 生成密钥
Storage 目录: 可读写  
Composer Package: 未导入  请安装 Composer 并执行 composer install 安装包
MySQL 连接: 失败  could not find driver
MySQL 数据表: 未导入  could not find driver
--------------------------------------------------------------------------------
[ 其他信息 ]
码小六版本：1.6.1
框架运行环境：无
框架调试开关：无
PHP 禁用函数：无
PHP 已编译模块：Core,date,libxml,openssl,pcre,zlib,filter,hash,pcntl,Reflection,SPL,sodium,session,standard,PDO,calendar,ctype,exif,fileinfo,ftp,gettext,iconv,json,Phar,posix,readline,shmop,sockets,sysvmsg,sysvsem,sysvshm,tokenizer,Zend OPcache
--------------------------------------------------------------------------------

## 报错日志
    - Root composer.json requires simplesoftwareio/simple-qrcode 1.3.* -> satisfiable by simplesoftwareio/simple-qrcode[1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - simplesoftwareio/simple-qrcode[1.3.0, ..., 1.3.3] require ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - 
日志目录：storage/logs
```

**Comment by wooyunwang** [comment]
打印code6的docker日志可以看到
Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18

**Comment by yoonper** [comment]
稍等 我测试一下

**Comment by yoonper** [comment]
Dockerfile：
```
apt-get install -y --allow-downgrades zip cron vim zlib1g=1:1.2.11.dfsg-1 zlib1g-dev libpng-dev;\
```
改为
```
apt-get install -y --allow-downgrades zip cron vim zlib1g=1:1.2.11.dfsg-1+deb10u1 zlib1g-dev libpng-dev;\
```

重新编译启动试试
