### ISSUE TITLE
队列任务 永远第一个执行中 ...

### ISSUE THREAD

**Issue by yiiing** [4x99/code6#229]
## 安装方式
源码安装

## 问题描述
队列任务 永远第一个执行中 
![image](https://user-images.githubusercontent.com/8021891/190980341-5467a976-62a0-418f-aa9b-3751da5cd08a.png)

## 运行环境
```
[ 环境检查 ]
PHP 版本: 7.3.31  
PDO 扩展: 已安装  
Laravel 密钥: 已生成  
Storage 目录: 可读写  
Composer Package: 已导入  
MySQL 连接: 成功  
MySQL 数据表: 已导入  
```

## 报错日志
```
日志内容为空
```

**Comment by yoonper** [comment]
检查下 CRON 任务是否正确配置

**Comment by yiiing** [comment]
![image](https://user-images.githubusercontent.com/8021891/190981749-c1cff2c2-8b71-4cf1-879d-0b4218bde110.png)

log 有执行任务信息的啊

**Comment by yoonper** [comment]
job-add 是把任务加到队列
还有一个 job-run 是执行队列任务，看你的日志列表没有

**Comment by yiiing** [comment]
![image](https://user-images.githubusercontent.com/8021891/190984828-666e3aa2-83a5-4b7a-930b-11613c92a60e.png)
已经添加 CRON 按照文档的

**Comment by yoonper** [comment]
code6-2022-09-19.log 没有错误信息吗

**Comment by yoonper** [comment]
也检查下 PHP 的报错日志

**Comment by yiiing** [comment]
![image](https://user-images.githubusercontent.com/8021891/190990142-c5c050be-571b-4194-bc2b-e3892ea01673.png)

**Comment by yoonper** [comment]
php fileinfo 扩展模块安装有问题，搜一下相关教程重新安装
