### ISSUE TITLE
登录不进去了，提示SQLSTATE报错

### ISSUE THREAD

**Issue by wtt502** [4x99/code6#230]
## 安装方式
Docker 安装 
## 问题描述
用户名密码登录不进去
![image](https://user-images.githubusercontent.com/50694663/191197368-af3d46fb-1142-40b0-a3a8-8fdfdc98009d.png)

## 运行环境
```
请复制 php doctor.php 运行结果
```

## 报错日志
无报错日志

```
日志目录：storage/logs
```

**Comment by yoonper** [comment]
数据库连接失败

**Comment by yoonper** [comment]
参考常见问题#1

**Comment by wtt502** [comment]
请问删除当前容器，创建新的容器，对原来的数据有影响吗

**Comment by yoonper** [comment]
不影响，数据都在 MySQL

**Comment by wtt502** [comment]
楼主，搞了2天了，一直连不上数据库，容器和镜像都删了重装。还是连不上，能支持一下吗？WX：273205244

**Comment by yoonper** [comment]
常见问题#1 第 1 点的方法都尝试过了吗

**Comment by wtt502** [comment]
大佬，重试过好多次了，就是起不来，帮忙看看，谢谢

**Comment by yoonper** [comment]
这个问题已经很明确了，无法正常连接 MySQL
如果无法解决，可以尝试用 Docker-Compose 方式安装，此方式提供了 MySQL 容器。
https://github.com/4x99/code6/blob/master/doc/deploy-docker-compose.md
