### ISSUE TITLE
Encountered errors while bringing up the project.  正常docker-compose安装启动但报错了

### ISSUE THREAD

**Issue by Iceqaq** [4x99/code6#232]
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.mysql.ports contains an invalid type, it should be a number, or an object
services.code6.ports contains an invalid type, it should be a number, or an object

![image](https://user-images.githubusercontent.com/43596990/195575318-5b304c9e-b3aa-4ab9-9a11-5e3104eb80b3.png)

**Comment by GallopYD** [comment]
请提供一下 docker-compose 版本，及容器启动日志。
