### ISSUE TITLE
无法扫描出新记录

### ISSUE THREAD

**Issue by jumpboy20** [4x99/code6#234]
配了4个token，5个扫描关键字，配置一个文件只记录一次，扫5页，间隔60分钟，第一次扫描都有新纪录，但是往后很多天都没新记录了，请问这是正常的么？我也没发现日志在什么地方，麻烦帮忙解答一下，谢谢。

**Comment by yoonper** [comment]
日志在 `storage/logs` 目录

**Comment by yoonper** [comment]
1. 检查日志是否正常
2. 访问 `https://github.com/search?o=desc&q=关键字&s=indexed&type=Code` 确认是否真的有新记录

**Comment by jumpboy20** [comment]
日志目录是空的，没文件。
手工搜了下，是有600多条记录的。
扫描页数增加了些，新增了几条。
问下，扫描逻辑会过滤掉已经处理过的记录么？

**Comment by yoonper** [comment]
日志要在容器内查看，正常不应该为空
重复文件不会再记录
扫描页数增加有新增几条说明应该是正常的，你看下我上面发的第 2 点，看是否是关键字真的就没有新记录

**Comment by jumpboy20** [comment]
多谢回复，日志看到了
您发的第二点，我试了，有些关键字没有新纪录是对的，有一个有600多条，目前只扫出来100多条，估计设置的扫描页数不够多。

**Comment by yoonper** [comment]
嗯 扫描是按索引时间倒序取前 n 页
