### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by YuehWenn** [4x99/code6#238]
## 安装方式
Docker-Compose 安装、Docker 安装

## 问题描述
请描述遇到的问题..
docker安装
一开始用docker安装，无法连接到Windows宿主机上安装的mariadb，我尝试过将172.17.0.1换成172.17.0.2或host.docker.internal或vEthernet的IP，也都在mariadb添加了用户和权限，但都无法连接上数据库

后面我使用docker-compose，生成的MySQL容器永远处在restart状态

最后我尝试将docker，mariadb等卸载，重启Windows，重新安装，这次docker部署一直excited

## 运行环境
Windows
docker 20.10.21
mariadb 10.10.2
```
请复制 php doctor.php 运行结果
```

## 报错日志
```
日志目录：storage/logs
```

**Comment by yoonper** [comment]
码小六没有在 win 环境下开发和测试，尽量不要用 Win

**Comment by YuehWenn** [comment]
唉:-(，好吧
