### ISSUE TITLE
写入账号报错

### ISSUE THREAD

**Issue by zhijunlu** [4x99/code6#239]
## 安装方式
Docker 安装 

## 问题描述
[root@YUM code6]# docker exec -it code6-server /bin/bash
root@72035cfe780c:/var/www/html# php artisan code6:user-add ***@ly.com  2***

Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18
root@72035cfe780c:/var/www/html# 

## 运行环境
root@72035cfe780c:/var/www/html# php doctor.php

--------------------------------------------------------------------------------
[ 环境检查 ]
PHP 版本: 7.4.33  
PDO 扩展: 已安装  
Laravel 密钥: 未生成  请执行命令 php artisan key:generate 生成密钥
Storage 目录: 可读写  
Composer Package: 未导入  请安装 Composer 并执行 composer install 安装包
MySQL 连接: 失败  SQLSTATE[HY000] [1045] Access denied for user 'code6'@'172.17.0.2' (using password: NO)
MySQL 数据表: 未导入  SQLSTATE[HY000] [1045] Access denied for user 'code6'@'172.17.0.2' (using password: NO)
--------------------------------------------------------------------------------
[ 其他信息 ]
码小六版本：1.6.2
框架运行环境：production
框架调试开关：false
PHP 禁用函数：无
PHP 已编译模块：Core,date,libxml,openssl,pcre,sqlite3,zlib,ctype,curl,dom,fileinfo,filter,ftp,hash,iconv,json,mbstring,SPL,PDO,pdo_sqlite,session,posix,readline,Reflection,standard,SimpleXML,Phar,tokenizer,xml,xmlreader,xmlwriter,mysqlnd,pdo_mysql,sodium

## 报错日志
[root@YUM code6]# cd storage/logs
[root@YUM logs]# ls
[root@YUM logs]# 

无日志

**Comment by yoonper** [comment]
Docker 容器启动有错误
删掉容器重新启动一个试试，或者 docker logs 命令查看日志

**Comment by zhijunlu** [comment]
[root@YUM logs]# docker logs -f code6-server

Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18
sed: -e expression #1, char 38: unknown option to `s'

Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18
cron: unrecognized service
docker-entrypoint.sh: line 18: crontab: command not found
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
Starting Apache httpd web server: apache2.


> Docker容器启动有错误 删除容器重新启动一个测试，或者docker日志命令查看日志

**Comment by yoonper** [comment]
启动容器的时候有报错吗
从日志上看 Dockerfile 的命令没有正确执行
