### ISSUE TITLE
搜索语法能够添加or规则和多个条件匹配吗

### ISSUE THREAD

**Issue by defaul0t** [4x99/code6#240]
比如，匹配 github.com language:go or language:java AND (password or pwd or passwd)

**Comment by yoonper** [comment]
支持多条件匹配，`AND` 和 `OR` 需要大写
我们在 `[ 任务配置 ]` 模块左上角的 `[ 关键字说明 ]` 里有一些基础说明
此外 `AND`、`NOT`、`OR` 最多只能使用 5 个，且查询语句不能超过 256 个字符
更多信息请参考 https://docs.github.com/cn/rest/search?apiVersion=2022-11-28

**Comment by defaul0t** [comment]
收到有交流群或者可以加vx吗

**Comment by yoonper** [comment]
目前没有群哈，有问题和建议都可以通过 issue 的方式提交 :D

**Comment by defaul0t** [comment]
我想匹配baidu.com 泄露的代码中包含敏感信息页面可以如下这样写吗,能列一个正确的吗

.baidu.com AND (password OR pwd OR passwd) NOT language:js NOT language:html

.baidu.com AND (password  pwd passwd)  NOT language:js NOT language:html

**Comment by yoonper** [comment]
`.baidu.com AND (password OR pwd OR passwd) NOT language:js NOT language:html`
这个就行吧，可通过 `https://github.com/search?o=desc&s=indexed&type=code&q=关键字` 预览扫描结果

**Comment by defaul0t** [comment]
好像不行
![1671010773156](https://user-images.githubusercontent.com/49946499/207560511-369c8d84-f0aa-426a-b1c9-43388c1a4c16.png)

**Comment by yoonper** [comment]
https://github.com/search?o=desc&s=indexed&type=code&q=.baidu.com%20AND%20(password%20OR%20pwd%20OR%20passwd)%20NOT%20language%3Ajs%20NOT%20language%3Ahtml

**Comment by defaul0t** [comment]
如何排除多个文件后缀以及匹配多个不同的关键字

![1671011474944](https://user-images.githubusercontent.com/49946499/207563259-c4cbbdc7-7e91-4ef6-b526-56a810a6687c.png)

**Comment by yoonper** [comment]
GitHub 对搜索限制较多，恐怕有些无法实现，具体你可以研究下 GitHub 的文档

**Comment by defaul0t** [comment]
我添加了6000个任务，到现在没有开始正常扫描
![1671090544474](https://user-images.githubusercontent.com/49946499/207802731-619f7add-953a-4c4a-95a4-a6af3c6cf5ff.png)

**Comment by yoonper** [comment]
下次扫描时间显示的是 16:00

**Comment by defaul0t** [comment]
不是的，一直没有最近扫描记录，我放一天了

![1671098457510](https://user-images.githubusercontent.com/49946499/207830249-8b7e984a-677b-49f1-a725-1493ab7c7d32.png)

**Comment by yoonper** [comment]
麻烦根据 issue 模板提供一下部署信息和日志

**Comment by defaul0t** [comment]
你加我vx吧，我把服务器发你，我不知道咋弄

**Comment by yoonper** [comment]
https://github.com/4x99/code6/issues/new
参照 isssue 模板提供相关信息

**Comment by defaul0t** [comment]
记录很多，没有办法全部删除吗，只能5050条的删除

**Comment by yoonper** [comment]
目前一次只能处理 50 条，如果有需要可以适当修改一下分页条数
https://github.com/4x99/code6/blob/master/resources/views/codeLeak/index.blade.php#LL9C3-L9C3
```
pageSize: 50
```
