### ISSUE TITLE
添加6800个任务无法扫描

### ISSUE THREAD

**Issue by defaul0t** [4x99/code6#241]
Docker 安装

## 问题描述
添加6800个任务无法扫描

## 运行环境
```
[ 环境检查 ]
PHP 版本: 7.4.33
PDO 扩展: 已安装
Laravel 密钥: 已生成
Storage 目录: 可读写
Composer Package: 已导入
MySQL 连接: 成功
MySQL 数据表: 已导入
--------------------------------------------------------------------------------
[ 其他信息 ]
码小六版本：1.6.2
框架运行环境：production
框架调试开关：false
PHP 禁用函数：无
PHP 已编译模块：Core,date,libxml,openssl,pcre,sqlite3,zlib,ctype,curl,dom,fileinfo,filter,ftp,hash,iconv,json,mbstring,SPL,PDO,pdo_sqlite,session,posix,readline,Reflection,standard,SimpleXML,Phar,tokenizer,xml,xmlreader,xmlwriter,mysqlnd,gd,pdo_mysql,sodium
```

## 报错日志
```
![1671152378219](https://user-images.githubusercontent.com/49946499/207998163-e3c71bc0-43ea-4519-ad91-8834df7b75fd.png)

![1671152405083](https://user-images.githubusercontent.com/49946499/207998211-08f185df-5d86-4c1f-a7e9-39cfe6a57a5f.png)

```

**Comment by defaul0t** [comment]
![1671152456414](https://user-images.githubusercontent.com/49946499/207998288-836daa37-dd63-4749-bd75-848fcf1c2a00.png)

![1671152469349](https://user-images.githubusercontent.com/49946499/207998315-5f53d8e7-3ef4-4c21-a73e-958e3fcc62c8.png)

**Comment by yoonper** [comment]
看日志是没到启动时间
你的配置是 7200 分钟，也就是 4 天才启动一次
界面上显示的下次启动时间超过 60 分钟显示有误，稍后会修复此问题，感谢反馈！

**Comment by defaul0t** [comment]
weibo.com AND  pwd AND language:conf  为什么使用这个语句，无法获取只有.conf后缀文件并且文本中同时包含weibo.com和pwd关键字的内容

**Comment by yoonper** [comment]
没有 conf 这个语言

**Comment by defaul0t** [comment]
出现个问题，扫描一周一直没动静和变化了
![1673082842261](https://user-images.githubusercontent.com/49946499/211143189-12d86ab8-d17f-459b-89f1-d21cfef1a719.png)
![1673082880074](https://user-images.githubusercontent.com/49946499/211143212-a7917583-27f0-40e2-8211-7ae5a5efd513.png)

**Comment by yoonper** [comment]
检查关键字是否有新数据或者提供更详细的日志信息

**Comment by defaul0t** [comment]
怎么检查

**Comment by defaul0t** [comment]
到现在只有12月23号的记录

**Comment by yoonper** [comment]
参考 #234

**Comment by defaul0t** [comment]
![1673084976493](https://user-images.githubusercontent.com/49946499/211144488-df883069-f30d-4964-bd96-937ed2dbc4e0.png)

有日志

**Comment by yoonper** [comment]
`job-run-$date.log` 的日志有吗
另外请检查一下关键字是否本身就没有新数据

**Comment by defaul0t** [comment]
job-run-$date.log 有的，今天的也有

![1673228371535](https://user-images.githubusercontent.com/49946499/211229420-30922634-a517-4e60-a093-6fd057b4cb6b.png)
