### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by L1NG0v0** [4x99/code6#245]
能否出一个批量导出功能，导出成execel

**Comment by yoonper** [comment]
感谢建议，我们会讨论下这个提议。

**Comment by yoonper** [comment]
已添加此功能，目前在 develop 分支 https://github.com/4x99/code6/commit/64b6f4577319f8a3a4805261fedcf6a75a5cf5be 随下一版本发布

**Comment by L1NG0v0** [comment]
好的 感谢
