### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by L1NG0v0** [4x99/code6#247]
1.添加处理时间模块，当修改状态时记录修改状态的时间，便于统计何时处理了这些仓库
2.筛选条件可以添加处理人、说明等查询条件

**Comment by yoonper** [comment]
1. 目前数据表 `code_leak` 有记录最后修改时间字段 `updated_at`，不知道对你是否有用
2. 查询条件可能接下去要把一些字段搜索框合并在一起，否则查询条件太多了，下个版本应该可以加上

**Comment by L1NG0v0** [comment]
ok好的 我看下

**Comment by L1NG0v0** [comment]
作者你好，考虑邮件推送的加密形式多选吗？现在遇到一个问题是邮件服务器是用ssl加密 平台使用tls导致无法建立链接

**Comment by yoonper** [comment]
ok，我跟进一下
临时处理方案：使用 webhook 方式请求，然后自己再发邮件

**Comment by GallopYD** [comment]
已跟进，会在下个版本增加加密方式选项

**Comment by L1NG0v0** [comment]
好的 感谢

**Comment by GallopYD** [comment]
方便留个QQ吗，上次邮件问题再跟你确认下。

**Comment by Ling-Huang-Get** [comment]
方便的 383417532
