### ISSUE TITLE
容器重启，重新登录提示报错

### ISSUE THREAD

**Issue by zhangk64** [4x99/code6#248]
## 安装方式
Docker 安装

## 问题描述
容器重启，登录页面输入账号密码，点击登录，提示报错如图
![image](https://user-images.githubusercontent.com/29709035/222068405-7e80c0b8-0a32-4d0c-9fef-b8c5721abf2e.png)
再次重启，就出现如下：
![image](https://user-images.githubusercontent.com/29709035/222068997-cb9e650d-0077-40c1-a4b9-2205ababc78e.png)
可能是dbuser没有清空初始化？

## 运行环境
centos7，宿主机安装mysql5.7，Docker version 23.0.1,
请复制 php doctor.php 运行结果
```

## 报错日志
```
日志目录：storage/logs
```

**Comment by zhangk64** [comment]
**

[ ] 临时解决方案

**
docker rm容器，重新run一个新容器，不要重启。

**Comment by zhangk64** [comment]
### 临时解决方案
docker rm容器，重新run一个新容器，不要重启。

**Comment by GallopYD** [comment]
已跟进，会在下个版本修复

**Comment by GallopYD** [comment]
已跟进，会在下个版本修复

**Comment by zhangk64** [comment]
> 已跟进，会在下个版本修复

感谢。

**Comment by wtt502** [comment]
![图片](https://user-images.githubusercontent.com/50694663/223035435-aabfdc2d-5ba2-468e-b87f-fe90260d3e4a.png)
大佬你好，我这边有任务在一直处于待执行中，导致其他任务都是待执行，请问这个怎么处理

**Comment by yoonper** [comment]
> ![图片](https://user-images.githubusercontent.com/50694663/223035435-aabfdc2d-5ba2-468e-b87f-fe90260d3e4a.png) 大佬你好，我这边有任务在一直处于待执行中，导致其他任务都是待执行，请问这个怎么处理

任务是按队列逐个执行，可能是没有正常执行任务，麻烦通过 [New issue](https://github.com/4x99/code6/issues/new) 提交问题，顺便附带相应的日志信息，以便跟进。

**Comment by yoonper** [comment]
v1.6.4 已修复此问题，可更新至此版本。
