### ISSUE TITLE
任务列表停止运行

### ISSUE THREAD

**Issue by wtt502** [4x99/code6#252]
## 安装方式
Docker 安装

## 问题描述
请描述遇到的问题..
2023.3.6 13:51开始所有扫描都停止运行了，查看任务列队，是因为有一个任务一直在执行者，导致其他任务都没有执行
![image](https://user-images.githubusercontent.com/50694663/223631713-f4fb35bc-dcaf-490b-921b-2aaaa92bc88f.png)
[](url)
![image](https://user-images.githubusercontent.com/50694663/223631682-067a4689-442e-48ef-8c50-95ce88a625c2.png)

## 运行环境
```
请复制 php doctor.php 运行结果
```
centos7  docker  

## 报错日志
```
日志目录：storage/logs

```
[job-run-2023-03-06.log](https://github.com/4x99/code6/files/10917663/job-run-2023-03-06.log)

**Comment by yoonper** [comment]
如果有 `code6-*.log` 和 `job-add-*.log` 也麻烦提供一下。

**Comment by wtt502** [comment]
已全部上传，辛苦帮忙看看，谢谢

[notify-2023-03-06.log](https://github.com/4x99/code6/files/10917790/notify-2023-03-06.log)
[code6-2023-03-06.log](https://github.com/4x99/code6/files/10917791/code6-2023-03-06.log)
[job-add-2023-03-06.log](https://github.com/4x99/code6/files/10917793/job-add-2023-03-06.log)
[job-run-2023-03-06.log](https://github.com/4x99/code6/files/10917796/job-run-2023-03-06.log)

**Comment by GallopYD** [comment]
由于待执行队列中的，对应 ```https://open .work.weixin.qq.com/wwopen/sso/arConnect``` 这个任务配置被删，导致任务更新失败，阻塞了后面任务，临时解决方案：增加 ```https://open .work.weixin.qq.com/wwopen/sso/arConnect``` 这个任务，等待队列中这个任务执行完再删除该关键字。

会在下个版本修复此问题。

**Comment by wtt502** [comment]
10分钟前，重新添加了这个任务，看起来也是执行不起来的。
![image](https://user-images.githubusercontent.com/50694663/223651250-9e541f1a-56d3-4e83-8e7b-55873b00015d.png)

**Comment by GallopYD** [comment]
可以将 ```queue_job``` 这张表清空，然后再试试是否正常执行。

**Comment by wtt502** [comment]
这表在哪？
把项目重启一下，能不能正常运行呢？

**Comment by GallopYD** [comment]
将数据库中```queue_job ```这张表清空

项目重启还是不能正常运行，因为队列表中还有脏数据

**Comment by wtt502** [comment]
感谢大佬，删除了表中多余的数据就跑起来了

**Comment by yoonper** [comment]
v1.6.4 已修复此问题，可更新至此版本。
