### ISSUE TITLE
Docker-Compose 部署方式，宿主机是否需要安装mysql

### ISSUE THREAD

**Issue by zhangk64** [4x99/code6#256]
## 安装方式
Docker-Compose 安装、Docker 安装 或 源码安装

## 问题描述
[Docker-Compose部署，code6-mysql 容器报错
![image](https://user-images.githubusercontent.com/29709035/227125376-0f63428c-ce7d-4732-afe1-508fac9740cf.png)
![image](https://user-images.githubusercontent.com/29709035/227125642-4d4652ed-8a71-4f09-b832-244b82119ba7.png)

## 运行环境
centos7

```

## 报错日志
```
日志目录：storage/logs
```

**Comment by yoonper** [comment]
宿主机不用安装 MySQL，Docker-Compose 会自动创建 MySQL 容器挂载到配置的宿主机 `MYSQL_VOLUME_PATH` 目录
如果有报错可以查看一下报错内容

**Comment by yoonper** [comment]
有一个容易导致 MySQL 容器启动失败的地方
`.env.docker-compose` 的 `MYSQL_USER` 不能设置为 `root`，文档里有说明。

**Comment by zhangk64** [comment]
> 



> 

好像是挂载目录有文件目录，换了个空文件目录就好了
