### ISSUE TITLE
安装依赖composer报错

### ISSUE THREAD

**Issue by A1rkor** [4x99/code6#260]
## 安装方式
Docker-Compose 安装

## 问题描述
使用命令composer install --no-dev --optimize-autoloader安装依赖报错怎么解决？
![image](https://user-images.githubusercontent.com/128011364/229464576-691da108-6102-448f-aa51-89a99da0cf94.png)

## 运行环境
```
请复制 php doctor.php 运行结果
```

## 报错日志
```
日志目录：storage/logs
```

**Comment by yoonper** [comment]
这似乎不是通过 Docker-Compose 安装，镜像的 PHP 版本是 7.4，你的 PHP 版本是 8.2.2

**Comment by A1rkor** [comment]
是安装docker-compose安装文档步骤操作的，安装依赖时没有composer命令，使用apt install compsoer安装就会安装php8版本的

**Comment by A1rkor** [comment]
我是碰到这个问题安装解决方法操作的
![image](https://user-images.githubusercontent.com/128011364/229466831-521fe1e8-9b87-4737-b0f5-d35328659315.png)

**Comment by yoonper** [comment]
他应该是源码安装
正常 Docker-Compose 不需要你再安装 Composer，Dockerfile 已经有相关步骤了

**Comment by A1rkor** [comment]
感谢，已解决，ubuntu会报错，使用kali安装成功了
