### ISSUE TITLE
请问【任务配置】-【扫描页数】，这个参数具体是指什么？

### ISSUE THREAD

**Issue by ManUtdPudge** [4x99/code6#263]
## 安装方式
Docker-Compose 

## 问题描述
请问【任务配置】-【扫描页数】，这个参数具体是指什么？

![QQ截图20230413182106](https://user-images.githubusercontent.com/60635948/231730910-ed37a2b5-cc98-4da5-8b47-9fffa630c959.jpg)

**Comment by yoonper** [comment]
GitHub 按 indexed 时间即索引时间倒序排序
新提交的代码会在最新页出现，所以每次扫描时只扫前 n 页基本上就能扫到新记录，而不用把全量扫描

**Comment by yoonper** [comment]
不过 GitHub 新版搜索已经不再支持排序
4 月 10 日已经弃用 `sort` 和 `order` 参数，我们在跟进这个问题

**Comment by ManUtdPudge** [comment]
好的谢谢
