### ISSUE TITLE
增加用户报错

### ISSUE THREAD

**Issue by cpkkcb** [4x99/code6#35]
docker run -d  -p 8088:80  -e MYSQL_HOST=127.0.0.1  -e MYSQL_PORT=3306  -e MYSQL_DATABASE=code6  -e MYSQL_USERNAME=root  。。。
  
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `user` where (`email` = 13111111@qq.com) limit 1)

数据库用户权限
mysql>  select user,host from user;
+------------------+-----------+
| user             | host      |
+------------------+-----------+
| root             | %         |
| debian-sys-maint | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |

**Comment by yoonper** [comment]
MySQL 是装在宿主机吗？
MYSQL_HOST = 127.0.0.1 连不上宿主机 MySQL，你在宿主机执行 ifconfig 看看 docker0 的 IP，有可能是 172.17.0.1，在 Docker 容器里 telnet 这个 IP，能通了删掉容器重新启动一个

**Comment by cpkkcb** [comment]
宿主机安装的mysql,docker0 ip:172.18.0.1 
 docker run -d  -p 8088:80  -e MYSQL_HOST=172.18.0.1  -e MYSQL_PORT=3306  -e MYSQL_DATABASE=code6 

能ping通 
PING 172.18.0.1 (172.18.0.1) 56(84) bytes of data.
64 bytes from 172.18.0.1: icmp_seq=1 ttl=64 time=0.072 ms
64 bytes from 172.18.0.1: icmp_seq=2 ttl=64 time=0.065 ms
但是依然报同样的错误

**Comment by yoonper** [comment]
telnet 172.18.0.1 3306 能通吗
通常连不上都是 iptable 防火墙 和 MySQL 未授权 这几个问题

**Comment by yoonper** [comment]
还有一个可能的原因
MySQL 配置文件绑定了 127.0.0.1，注释掉这行（如果有的话）：
```
bind-address = 127.0.0.1
```

**Comment by cpkkcb** [comment]
👌
