### ISSUE TITLE
令牌配置模块增加未知状态

### ISSUE THREAD

**Issue by yoonper** [4x99/code6#36]
原因：目前令牌分为 `正常` 与 `异常` 状态

其中 `异常` 状态包含两种情况：
1. 令牌真的异常
2. 因为国内网络原因请求 GitHub 失败导致异常（经常出现，所以状态时而正常时而异常）

为了更好区分，新增 `未知` 状态来标记第二种情况

**Comment by dgy85** [comment]
实测一直异常, 无法扫描

**Comment by yoonper** [comment]
> 实测一直异常, 无法扫描

进入容器查看一下运行日志：
```
docker exec -it code6-server /bin/bash
cat storage/logs/job-run-2020-06-17.log
```

**Comment by dgy85** [comment]
code6-2020-06-24.log的日志

[2020-06-24 12:50:01] production.WARNING: cURL error 7: Failed to connect to api.github.com port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"token":"------删除----"}

测试了下
root@76ee3866d8bd:/var/www/html/storage/logs# curl -sSL https://api.github.com
{
  "current_user_url": "https://api.github.com/user",
  "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
  "authorizations_url": "https://api.github.com/authorizations",
  "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
  "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://api.github.com/user/emails",
  "emojis_url": "https://api.github.com/emojis",
  "events_url": "https://api.github.com/events",
  "feeds_url": "https://api.github.com/feeds",
  "followers_url": "https://api.github.com/user/followers",
  "following_url": "https://api.github.com/user/following{/target}",
  "gists_url": "https://api.github.com/gists{/gist_id}",
  "hub_url": "https://api.github.com/hub",
  "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://api.github.com/issues",
  "keys_url": "https://api.github.com/user/keys",
  "label_search_url": "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
  "notifications_url": "https://api.github.com/notifications",
  "organization_url": "https://api.github.com/orgs/{org}",
  "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_teams_url": "https://api.github.com/orgs/{org}/teams",
  "public_gists_url": "https://api.github.com/gists/public",
  "rate_limit_url": "https://api.github.com/rate_limit",
  "repository_url": "https://api.github.com/repos/{owner}/{repo}",
  "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://api.github.com/gists/starred",
  "user_url": "https://api.github.com/users/{user}",
  "user_organizations_url": "https://api.github.com/user/orgs",
  "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
}

token和网络环境应该没问题,,同时安装的GitHub-Monitor可以正常扫

**Comment by yoonper** [comment]
偶尔连不上应该不影响扫描任务，可以多配置几个 token，任务间隔调低
我们也会对 GitHub API 请求频率做优化，请关注后续的版本更新

**Comment by dgy85** [comment]
添加了多个token, 任务运行的时候都提示异常

**Comment by yoonper** [comment]
扫描结果一条记录都没有吗

**Comment by yoonper** [comment]
方便的话留个 QQ，我看一下

**Comment by KangD1W2** [comment]
php artisan code6:user-add <邮箱> <密码>出错，连接不上mysql数据库，能否出个教程？
