### ISSUE TITLE
增加通知预警

### ISSUE THREAD

**Issue by devsecops-SRC** [4x99/code6#37]

**Comment by yoonper** [comment]
消息通知在我们的开发计划中
我们在评估是只通知 “有 x 条未处理” 还是通知具体扫描详情

**Comment by kingsec666** [comment]
通知最好和后台联动
有数据量化

**Comment by yoonper** [comment]
因为扫描记录没有单独展示页面，所以不是特别好联动

**Comment by kingsec666** [comment]
> 企业微信
> 钉钉通知
> 
> ![image](https://user-images.githubusercontent.com/50866822/85379061-e702bb00-b56d-11ea-805c-ba9643c2d8a6.png)

**Comment by kingsec666** [comment]
请大佬优化 通知     界面可以用vue前端美化下么

**Comment by yoonper** [comment]
> 请大佬优化 通知 界面可以用vue前端美化下么

我们开发第一版用的是 AntDesign Vue，后来决定使用 ExtJS，应该不会再用 Vue 重写了。

**Comment by yoonper** [comment]
消息通知已发布
