### ISSUE TITLE
能否新增两个功能？

### ISSUE THREAD

**Issue by EmmHoHo** [4x99/code6#52]
1、筛选出根据仓库关键字筛选；目前的功能为爬到的信息有仓库关键字信息，但筛选条件没有。
2、扫描结果列能否增加一个新增一个字段：“文件的最近更新时间”，同样可对此字段筛选查看

**Comment by yoonper** [comment]
第 1 个问题可否描述的更清晰一些

**Comment by EmmHoHo** [comment]
根据 “仓库描述” 字段筛选

**Comment by yoonper** [comment]
1. 可以，在下个版本更新
2. 对于 GitHub，每次文件编辑都会产生新的记录，如果 [ 任务配置 ] 中的 [ 扫描结果 ] 设置为 “记录文件的每个版本”，则扫描时间可以近似等于文件更新时间

**Comment by EmmHoHo** [comment]
感谢！辛苦！第二点，原因是我在应用中发现扫到了较早版本的文件如12年等等，这些信息实际是没有价值的，但是目前的情况是又需要逐条点开查看

**Comment by yoonper** [comment]
这个问题我们有关注到，GitHub 按更新时间排序，偶尔会出现乱序问题（即出现早期的索引结果），之前给 GitHub 写了邮件没有收到回复，我们跟进下。

**Comment by EmmHoHo** [comment]
多谢！

**Comment by yoonper** [comment]
v1.4.0 已发布，第 1 点已支持
第 2 点时间乱序是 GitHub 的问题，因为国内网络原因，我们需要控制向 GitHub 请求的频率，无法通过接口请求每一个文件判断更新时间，故暂时无法解决
