### ISSUE TITLE
链接数据库报错

### ISSUE THREAD

**Issue by shu1qin9** [4x99/code6#54]
报错信息：
In Connection.php line 671:
                                                                                                                 
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.2' (using password: YES) (SQL: select * from `  
  user` where (`email` = liushuiqing@shiqiao.com) limit 1)                                                       
                                                                                                                 

In Connector.php line 70:
                                                                                           
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.2' (using password: YES) 

我已经讲MYSQL_HOST写成了docker0的IP地址了，但是为什么进入到容器中，IP地址还是不变呢

**Comment by yoonper** [comment]
IP 地址还是不变指的是什么
Access denied 可以参考常见问题 1 处理

**Comment by shu1qin9** [comment]
> IP 地址还是不变指的是什么
> Access denied 可以参考场景问题 1 处理

就是在创建容器的时候，-e MYSQL_HOST这样指定的MySQL链接IP ，进入到容器之后没有发生变化
好的，我去试一试，谢谢您

**Comment by yoonper** [comment]
通过 `-e MYSQL_HOST` 方式启动容器，进入容器后可以 `cat .env` 看配置是否正确
如果正确连不上请参考常见问题 1 处理

**Comment by shu1qin9** [comment]
> 通过 `-e MYSQL_HOST` 方式启动容器，进入容器后可以 `cat .env` 看配置是否正确
> 如果正确连不上请参考常见问题 1 处理

如果不正确的话，我是不是可以直接从docker外部写一个.env文件然后放进去呢

**Comment by yoonper** [comment]
可以，配置正确后执行下面语句自动导入数据表：
```
php artisan migrate --force
```

**Comment by shu1qin9** [comment]
> 可以，配置正确后执行下面语句自动导入数据表：
> 
> ```
> php artisan migrate --force
> ```

好嘞，了解，谢谢您
