### ISSUE TITLE
请问是不是GitHub修改了匹配策略

### ISSUE THREAD

**Issue by TimCong** [4x99/code6#60]
现在的任务，扫描的结果都是模糊匹配的了，不能精确匹配。

**Comment by yoonper** [comment]
1.4.0 版本开始支持 GitHub 高级搜索语法，若原有扫描关键字包含空格、逗号等特殊符号，请给关键字加上双引号，详见 [ 任务配置 ] - [ 关键字说明 ]

**Comment by yoonper** [comment]
我们也收到了 < 1.4.0 版本相同问题的反馈，经过排查，发现不同的 GitHub Access Token 请求搜索相同关键字返回结果不一致，部分账号返回大量非相关搜索结果，下面是 GitHub Support 团队给我的回复：
```
Hi YoonPer,

I believe what has happened here is that some of your accounts were transitioned to new search architecture that we are in the process of rolling out, and some were still using the old architecture.

In a totally unrelated coincidence, the new search architecture has actually been turned off this morning, which means all accounts are currently using the old architecture. That means that this is an optimal time to do some testing -- can you check whether you now get the same results from both accounts?

Thanks,

Tammy
GitHub Support
```

GitHub 在做新搜索架构的灰度测试，部分账号使用了新搜索，但是有些问题，目前 GitHub 已经关闭了新搜索，请求接口恢复正常。

**Comment by TimCong** [comment]
> 我们也收到了 < 1.4.0 版本相同问题的反馈，经过排查，发现不同的 GitHub Access Token 请求搜索相同关键字返回结果不一致，部分账号返回大量非相关搜索结果，下面是 GitHub Support 团队给我的回复：
> 
> ```
> Hi YoonPer,
> 
> I believe what has happened here is that some of your accounts were transitioned to new search architecture that we are in the process of rolling out, and some were still using the old architecture.
> 
> In a totally unrelated coincidence, the new search architecture has actually been turned off this morning, which means all accounts are currently using the old architecture. That means that this is an optimal time to do some testing -- can you check whether you now get the same results from both accounts?
> 
> Thanks,
> 
> Tammy
> GitHub Support
> ```
> 
> GitHub 在做新搜索架构的灰度测试，部分账号使用了新搜索，但是有些问题，目前 GitHub 已经关闭了新搜索，请求接口恢复正常。

正常了吗？这两天库都快炸了，都是不相关的告警量。我这边出现这个问题就是我提问的那天，那天的告警突然猛增，之后到现在都不是精确匹配的~

**Comment by yoonper** [comment]
1. 如果已升级了码小六 1.4.0 版本，关键字有包含特殊符号的，给关键字加上双引号

2. 如果未升此问题应该在 25 - 26 号恢复正常了（GitHub 临时下线了新搜索，他们搜索团队说异常结果不是预期行为，会跟进检查）

3. 如果需要删除相关非正常结果，可以根据 `created_at` 字段删除 `code_leak` 和 `code_fragment` 表

**Comment by TimCong** [comment]
> 1. 如果已升级了码小六 1.4.0 版本，关键字有包含特殊符号的，给关键字加上双引号
> 2. 如果未升此问题应该在 25 - 26 号恢复正常了（GitHub 临时下线了新搜索，他们搜索团队说异常结果不是预期行为，会跟进检查）
> 3. 如果需要删除相关非正常结果，可以根据 `created_at` 字段删除 `code_leak` 和 `code_fragment` 表

已经升级了1.4.0，特殊字符也已经加上双引号，还是很多不相关的告警。
关键字有：邮箱、IP、路径，均会产生大量误报。

**Comment by yoonper** [comment]
用配置的不同账号访问下面地址，看结果是否是你需要的，是否返回的条目不同：
```
https://github.com/search?o=desc&q="关键字"&s=indexed&type=Code
```

或者留个 QQ 我加你看下~

**Comment by coltisa** [comment]
我这边也出现类似问题，目前1.4.0版本配置了扫描任务，关键字中含有特殊符号如China@qq.com，遂加引号""括起来，如"China@qq.com"，但是结果出现了包含只有china字段的结果而并不是精确的China@qq.com

**Comment by yoonper** [comment]
> 我这边也出现类似问题，目前1.4.0版本配置了扫描任务，关键字中含有特殊符号如[China@qq.com](mailto:China@qq.com)，遂加引号""括起来，如"[China@qq.com](mailto:China@qq.com)"，但是结果出现了包含只有china字段的结果而并不是精确的[China@qq.com](mailto:China@qq.com)

不精确返回 “China@qq.com” 是正常的，GitHub 搜索使用的是 ES 集群，会忽略 @ 等特殊字符

**Comment by yoonper** [comment]
> 我这边也出现类似问题，目前1.4.0版本配置了扫描任务，关键字中含有特殊符号如[China@qq.com](mailto:China@qq.com)，遂加引号""括起来，如"[China@qq.com](mailto:China@qq.com)"，但是结果出现了包含只有china字段的结果而并不是精确的[China@qq.com](mailto:China@qq.com)

不过似乎可以根据 GitHub 返回的代码片段做精确过滤，我跟进一下。

**Comment by coltisa** [comment]
> > 我这边也出现类似问题，目前1.4.0版本配置了扫描任务，关键字中含有特殊符号如[China@qq.com](mailto:China@qq.com)，遂加引号""括起来，如"[China@qq.com](mailto:China@qq.com)"，但是结果出现了包含只有china字段的结果而并不是精确的[China@qq.com](mailto:China@qq.com)
> 
> 不精确返回 “[China@qq.com](mailto:China@qq.com)” 是正常的，GitHub 搜索使用的是 ES 集群，会忽略 @ 等特殊字符

你好，你的任务关键字说明   2. 关键字有空格或其他符号（引号）："hello world"  是说有@等特殊符号可以加“”框起来吗，可能是我理解有误

**Comment by yoonper** [comment]
> > > 我这边也出现类似问题，目前1.4.0版本配置了扫描任务，关键字中含有特殊符号如[China@qq.com](mailto:China@qq.com)，遂加引号""括起来，如"[China@qq.com](mailto:China@qq.com)"，但是结果出现了包含只有china字段的结果而并不是精确的[China@qq.com](mailto:China@qq.com)
> > 
> > 
> > 不精确返回 “[China@qq.com](mailto:China@qq.com)” 是正常的，GitHub 搜索使用的是 ES 集群，会忽略 @ 等特殊字符
> 
> 你好，你的任务关键字说明 2. 关键字有空格或其他符号（引号）："hello world" 是说有@等特殊符号可以加“”框起来吗，可能是我理解有误

特殊符号在 GitHub 搜索是会被忽略的，但是还是建议加双引号
`"hello world"`、`hello world`、`"hello@world"` 的搜索结果是不一致的，你可以对比一下其中的差别。

`"hello world"` 的搜索结果：
```
https://github.com/search?o=desc&q=%22hello+world%22&s=indexed&type=Code
```

`hello world` 的搜索结果：
```
https://github.com/search?o=desc&q=hello+world&s=indexed&type=Code
```

`"hello@world"` 的搜索结果：
```
https://github.com/search?o=desc&q=%22hello%40world%22&s=indexed&type=Code
```

我们最近在测试二次过滤 GitHub 返回的搜索结果，后续再更新~
