### ISSUE TITLE
令牌状态一直是未知

### ISSUE THREAD

**Issue by liang960215** [4x99/code6#61]
添加了令牌和扫描任务，令牌状态一直是未知，扫描也不开始。我查看了下日志，只有code6-2020-12-17.log这一个日志文件，没有job开头的日志。

**Comment by yoonper** [comment]
是源码部署还是通过 Docker 运行
请确保 Crontab 这个任务能正常启动：
```
* * * * * cd <项目目录> && php artisan schedule:run >> /dev/null 2>&1
```

**Comment by liang960215** [comment]
我用的docker运行的，* * * * * cd <项目目录> && php artisan schedule:run >> /dev/null 2>&1 这条命令已经配置了
![image](https://user-images.githubusercontent.com/44635826/102456973-f70ed980-407c-11eb-9871-aa99cf535d89.png)

**Comment by liang960215** [comment]
OKOK,开始了，估计是网络问题！ 但是接口用量只有30，好少啊~
