### ISSUE TITLE
扫描前端没有状态，也一直没有结果

### ISSUE THREAD

**Issue by sttscc** [4x99/code6#62]
如图
![image](https://user-images.githubusercontent.com/7426149/104398143-2a179080-5589-11eb-8fb4-4fa4a300b74f.png)
![image](https://user-images.githubusercontent.com/7426149/104398164-31d73500-5589-11eb-8f86-6aa11a1fea6a.png)

**Comment by yoonper** [comment]
看下 `storage/logs` 的日志

**Comment by sttscc** [comment]
> 看下 `storage/logs` 的日志
日志显示任务一直在不停的启动、关闭
![image](https://user-images.githubusercontent.com/7426149/104398638-1d476c80-558a-11eb-8804-a347c29f3134.png)

**Comment by yoonper** [comment]
检查下 [ 任务配置 ] - [ 扫描间隔 ] 配置
如果无法解决麻烦留个 QQ

**Comment by sttscc** [comment]
检查了也没看出啥问题，我QQ1010698366，麻烦加下QQ联系下，谢谢

**Comment by skr-rks** [comment]
> 检查下[任务配置]-[扫描间隔]配置
> 如果无法解决麻烦留个QQ

我也遇到了同样的问题。创建任务后是需要等待多久呢？

**Comment by yoonper** [comment]
> > 检查下[任务配置]-[扫描间隔]配置
> > 如果无法解决麻烦留个QQ
> 
> 我也遇到了同样的问题。创建任务后是需要等待多久呢？

@sttscc 是因为配置了错误的关键字，所以没有结果。
麻烦贴一下 job-run 和 job-add 的日志看下

**Comment by skr-rks** [comment]
新建任务处后边的搜索关键字可以搜索的
![新建任务](https://user-images.githubusercontent.com/57212526/104672341-907fe880-571a-11eb-8391-36195fc590d7.png)

![job-run job-add](https://user-images.githubusercontent.com/57212526/104672374-a392b880-571a-11eb-83b4-d311de7513f4.png)

**Comment by yoonper** [comment]
扫描间隔 30 分钟，实际会在 0 分 / 30 分执行任务，看下对应时间的日志

**Comment by skr-rks** [comment]
> 扫描间隔 30 分钟，实际会在 0 分 / 30 分执行任务，看下对应时间的日志

这个截图就是刚修改了扫描参数后的

**Comment by yoonper** [comment]
扫描间隔是 30 分钟，下一次执行时间是 10:30，图中日志还未到执行时间。

**Comment by skr-rks** [comment]
好的，已经出现了。

**Comment by Scor009** [comment]
> 
> 
> 扫描间隔是 30 分钟，下一次执行时间是 10:30，图中日志还未到执行时间。

我这边出现同样的问题，方便帮忙看下么？QQ:1037566893

**Comment by yoonper** [comment]
> > 扫描间隔是 30 分钟，下一次执行时间是 10:30，图中日志还未到执行时间。
> 
> 我这边出现同样的问题，方便帮忙看下么？QQ:1037566893

楼主是配置错误，我联系你看下。
