### ISSUE TITLE
连接不上数据库？

### ISSUE THREAD

**Issue by gzcl** [4x99/code6#80]
试过：docker run -d -p 666:80 -e MYSQL_HOST=IP  ---这里的IP是宿主机的IP，还是宿主机的docker网关IP 172.17.0.1？

In Connection.php line 671:

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `user` where (`email` = xx@xx.com) limit 1)

In Connector.php line 70:

  SQLSTATE[HY000] [2002] Connection refused

**Comment by yoonper** [comment]
`MYSQL_HOST` 是 MySQL 主机，如果 MySQL 装在宿主机就是宿主机 IP（通常为 `172.17.0.1`）
出现 `Connection refused` 请参考置顶的 `常见问题`（#1）

**Comment by gzcl** [comment]
你好，终于找到原因了，/etc/mysql/mysql.conf.d/mysqld.cnf
里面绑定了127.0.0.1，注释掉就不报这个2002 错误了。不过会继续报一下错误：

root@76819b92e31a:/var/www/html# php artisan code6:user-add xx@xxxx.com xxxx

In Connection.php line 671:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'code6.user' doesn't exist (SQL: select * from `user` where (`email` = xx@xxxx.com) limit 1)


In Connection.php line 331:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'code6.user' doesn't exist


看了ISSUE ，这样解决： 启动容器的时候自动创建，如果启动时数据库连接不上则创建失败，可以重新启动一个容器或者在当前容器执行：

php artisan migrate


谢谢。

**Comment by yoonper** [comment]
启动容器的时候数据库连不上，自动导入数据表失败，可以重新启动一个新的容器，或者在当前容器执行：
```
php artisan migrate
```
