### ISSUE TITLE
通知处的配置密码能不能打码？

### ISSUE THREAD

**Issue by gzcl** [4x99/code6#81]
现在通知那里的邮件密码 授权码和一些接口配置，都是明文直接写着的，这样在企业内部比较容易泄密。能不能把这里密码等敏感字段模糊处理一下。

**Comment by yoonper** [comment]
下个版本优化

**Comment by yoonper** [comment]
v1.5.1 已经对部分敏感字段做模糊处理
但仅仅是将 `input` `type` 设置为 `password`，HTML 源码里还能看到，建议配置公共账号而非私人账号
