### ISSUE TITLE
是否可考虑增加主动扫描功能？

### ISSUE THREAD

**Issue by k4ubb** [4x99/code6#84]
现在只能定时扫描，希望可以增加随时能进行的主动扫描功能

**Comment by yoonper** [comment]
感谢建议！我们会讨论一下
目前可以将扫描间隔临时改为 1 分钟触发扫描

**Comment by test502git** [comment]
码小六是我用过目前最用的github监测工具了，有着完整的生命周期，我已经向全公司详细介绍这封工具的优点，自己也做了一些二次开发。
但有一个问题就是，邮件通知、或者其他通知，不会展示泄露数据，只显示一个数据，可否把泄露数据也一并放到通知中？？？
