### ISSUE TITLE
码小六更新

### ISSUE THREAD

**Issue by test502git** [4x99/code6#95]
看到码小六的功能也越来越完善，版本升级也挺快，
个人建议可以在页面中增加一个更新功能，这样当有新功能发布时，我直接直更新即可升级到最新功能

**Comment by yoonper** [comment]
一键更新目前不太现实，后续版本会考虑在首页增加新版本提示。

**Comment by byr0nchan** [comment]
建议首页，记录数字和解决数字，可以做成趋势分析图，按日期进行排列，一目了然

**Comment by yoonper** [comment]
> 建议首页，记录数字和解决数字，可以做成趋势分析图，按日期进行排列，一目了然

没数据时首页大量空白可能不太美观，不过倒是可以考虑增加图表趋势模块来展示，我们讨论下，感谢建议~

**Comment by byr0nchan** [comment]
什么时候考虑增加把“码云”、本地Gitlab作为监控对象吗？

**Comment by yoonper** [comment]
近期应该不会支持 GitHub 以外的平台
